import type { ServiceDefinition } from '../types';

export const CLEANING_SERVICES: ServiceDefinition[] = [
  {
    id: 'service-01',
    number: '01',
    title: '입주·이사청소 예상비용',
    slug: 'move-in-cleaning',
    categoryId: 'cleaning',
    categoryName: '청소·가사',
    ruleId: 'rule-move-in-cleaning',
    shortDesc: '분양 입주 및 이사 전후 주거공간 전문 청소 평당 단가 및 예상 견적',
    icon: '🧹',
    questions: [
      {
        id: 'area_pyeong',
        label: '공급면적 (평형)',
        type: 'number',
        defaultValue: 24,
        min: 5,
        max: 80,
        step: 1,
        unit: '평',
        helpText: '아파트, 빌라, 오피스텔의 공급면적(분양평수)을 입력하세요.',
        required: true,
      },
      {
        id: 'contamination_level',
        label: '집 내부 오염도',
        type: 'select',
        defaultValue: 'normal',
        options: [
          { label: '신축 첫입주 (분진·먼지 위주)', value: 'new_build', priceDelta: -20000, hint: '시멘트가루, 톱밥 제거 위주' },
          { label: '보통 (일반적인 거주 후 이사)', value: 'normal', priceDelta: 0, hint: '기본 생활 오염' },
          { label: '심한 오염 (기름때·묵은때·담배)', value: 'heavy', priceDelta: 50000, hint: '주방 기름때, 곰팡이 광범위' },
          { label: '공실 장기방치 (곰팡이·악취 극심)', value: 'severe', priceDelta: 100000, hint: '약품 특수세척 필요' },
        ],
        required: true,
      },
      {
        id: 'veranda_count',
        label: '베란다/발코니 수',
        type: 'select',
        defaultValue: '1',
        options: [
          { label: '없음 (확장형)', value: '0', priceDelta: -20000 },
          { label: '1개', value: '1', priceDelta: 0 },
          { label: '2개', value: '2', priceDelta: 30000 },
          { label: '3개 이상 (비확장 광폭)', value: '3', priceDelta: 60000 },
        ],
        required: true,
      },
      {
        id: 'additional_options',
        label: '추가 특수 청소 옵션',
        type: 'select',
        defaultValue: 'none',
        options: [
          { label: '추가 없음 (기본 청소)', value: 'none', priceDelta: 0 },
          { label: '새집증후군 피톤치드 연무', value: 'phytoncide', priceDelta: 50000, hint: '살균 및 탈취 시공' },
          { label: '가전 내부 청소 (오븐·냉장고 내부)', value: 'appliance', priceDelta: 60000, hint: '분해 스팀 살균' },
          { label: '피톤치드 + 창문 스티커/시트지 제거', value: 'full_package', priceDelta: 100000 },
        ],
        required: false,
      },
    ],
    evidence: {
      provider: '숨고(Soomgo) 이사/입주 청소업체 시세 빅데이터',
      sourceUrl: 'https://soomgo.com/prices/%EC%9D%B4%EC%82%AC-%EC%9E%85%EC%A3%BC-%EC%B2%AD%EC%86%8C-%EC%97%85%EC%B2%B4',
      basePrice: 250000,
      minPrice: 140000,
      maxPrice: 420000,
      priceUnit: '공급면적 평당 11,000원 ~ 14,000원 (24평 평균 25만)',
      vatIncluded: true,
      travelFeeIncluded: true,
      materialsIncluded: true,
      surveyedAt: '2026-09-01',
      lastVerifiedAt: '2026-10-09',
      verificationStatus: 'verified',
      reliabilityLevel: 'high',
      sourceType: 'platform_average',
      notes: '숨고 실거래 평균 250,000원(최저 140,000원~최고 420,000원). 복층/외창 닦기/스티커 제거는 현장 추가요금 발생 가능.',
    },
    seo: {
      title: '입주·이사청소 예상비용 견적 계산기 | 바로견적',
      description: '아파트, 빌라, 오피스텔 입주청소 및 이사청소 평당 예상비용과 오염도별 추가금 조건을 간편하게 계산해보세요.',
      keywords: ['입주청소 비용', '이사청소 견적', '아파트 입주청소 평당가격', '오피스텔 청소비용', '입주청소 추가요금'],
      h1: '입주·이사청소 예상비용 계산기',
      canonicalPath: 'https://quote.info-myview.co.kr/estimate/move-in-cleaning/',
      faq: [
        {
          question: '입주청소와 이사청소의 차이는 무엇인가요?',
          answer: '입주청소는 신축 건물 준공 후 남아있는 시멘트 가루, 톱밥, 분진, 페인트 자국 등을 제거하는 작업이며, 이사청소는 이전 거주자가 남긴 기름때, 곰팡이, 생활 찌든 때를 약품으로 소독 세척하는 작업입니다.',
        },
        {
          question: '평당 청소 비용 산정 기준은 전용면적인가요, 공급면적인가요?',
          answer: '청소 업계는 관례상 분양면적(공급면적)을 기준으로 평당 가격을 책정합니다. 베란다, 다용도실, 창틀 등 서비스 공간이 청소 범위에 포함되기 때문입니다.',
        },
        {
          question: '외창(바깥 유리창) 닦기도 기본 견적에 포함되나요?',
          answer: '아닙니다. 안전 문제와 장비 사용으로 인해 실내에서 닿는 안쪽 창문만 기본 포함되며, 바깥쪽 외창 닦기는 특수 장비가 필요하여 별도 추가요금이 부과됩니다.',
        },
        {
          question: '현장에서 추가 요금이 발생하는 대표적인 경우는 무엇인가요?',
          answer: '창틀 곰팡이가 극심하거나, 창문에 뽁뽁이/단열시트지/스티커가 부착된 경우, 시스템 에어컨 필터 및 냉장고 내부 등 가전 내부 분해 청소를 요청할 때 추가 요금이 발생합니다.',
        },
      ],
    },
  },
  {
    id: 'service-05',
    number: '05',
    title: '에어컨 분해청소 비용',
    slug: 'air-conditioner-cleaning',
    categoryId: 'cleaning',
    categoryName: '청소·가사',
    ruleId: 'rule-ac-cleaning',
    shortDesc: '벽걸이, 스탠드, 2in1, 천장형 시스템 에어컨 고압 세척 및 살균 소독 비용',
    icon: '❄️',
    questions: [
      {
        id: 'ac_type',
        label: '에어컨 유형',
        type: 'select',
        defaultValue: 'stand',
        options: [
          { label: '벽걸이형 (일반/원룸용)', value: 'wall', priceDelta: 70000, hint: '소형 단독 제품' },
          { label: '스탠드형 (가정용)', value: 'stand', priceDelta: 130000, hint: '일반 거실 스탠드' },
          { label: '2in1 (스탠드 1대 + 벽걸이 1대)', value: '2in1', priceDelta: 180000, hint: '패키지 할인 적용' },
          { label: '천장형 시스템 에어컨 (1Way/4Way)', value: 'system', priceDelta: 120000, hint: '아파트·상가 천장 매립형' },
        ],
        required: true,
      },
      {
        id: 'unit_count',
        label: '청소 대수',
        type: 'number',
        defaultValue: 1,
        min: 1,
        max: 8,
        step: 1,
        unit: '대',
        helpText: '동일 장소에서 함께 청소할 에어컨 대수를 선택하세요 (다대수 할인 반영).',
        required: true,
      },
      {
        id: 'cleaning_scope',
        label: '분해 청소 범위',
        type: 'select',
        defaultValue: 'deep',
        options: [
          { label: '기본 분해 (필터·커버·송풍팬 분해 세척)', value: 'normal', priceDelta: 0 },
          { label: '완전 분해 (냉각핀 고압세척 + 열교환기 약품살균)', value: 'deep', priceDelta: 20000, hint: '추천: 곰팡이 냄새 완벽 제거' },
          { label: '프리미엄 살균 (완전분해 + UV자외선 + 피톤치드 코팅)', value: 'premium', priceDelta: 40000 },
        ],
        required: true,
      },
    ],
    evidence: {
      provider: '숨고(Soomgo) 에어컨 청소 시세 빅데이터',
      sourceUrl: 'https://soomgo.com/prices/%EC%97%90%EC%96%B4%EC%BB%A8-%EC%B2%AD%EC%86%8C',
      basePrice: 120000,
      minPrice: 60000,
      maxPrice: 260000,
      priceUnit: '대당 60,000원 ~ 260,000원 (스탠드 평균 12만)',
      vatIncluded: true,
      travelFeeIncluded: true,
      materialsIncluded: true,
      surveyedAt: '2026-09-01',
      lastVerifiedAt: '2026-10-09',
      verificationStatus: 'verified',
      reliabilityLevel: 'high',
      sourceType: 'platform_average',
      notes: '숨고 실거래 평균 120,000원(벽걸이 최저 60,000원, 스탠드 120,000원, 2in1/시스템 최고 260,000원). 2대 이상 시 다대수 할인 적용.',
    },
    seo: {
      title: '에어컨 분해청소 비용 견적 계산기 (벽걸이/스탠드/시스템) | 바로견적',
      description: '벽걸이, 스탠드, 천장형 시스템 에어컨 분해청소 및 고압 살균 세척 예상비용과 대수별 견적을 확인하세요.',
      keywords: ['에어컨 청소비용', '에어컨 분해청소 견적', '스탠드 에어컨 청소', '2in1 에어컨 청소비', '시스템 에어컨 청소'],
      h1: '에어컨 분해청소 비용 계산기',
      canonicalPath: 'https://quote.info-myview.co.kr/estimate/air-conditioner-cleaning/',
      faq: [
        {
          question: '에어컨 청소는 필터만 닦으면 안 되나요?',
          answer: '필터 뒤쪽의 냉각핀(열교환기)과 송풍팬 내부에 곰팡이와 유해균이 서식하므로, 고압 물세척과 전용 약품 살균을 거치는 분해 청소를 해야 냄새와 세균이 근본적으로 해결됩니다.',
        },
        {
          question: '청소 작업 소요 시간은 얼마나 걸리나요?',
          answer: '벽걸이 에어컨은 약 40분~1시간, 스탠드형은 1시간~1시간 30분, 2in1은 약 2시간~2시간 30분 정도 소요됩니다.',
        },
        {
          question: '에어컨 분해 청소 주기는 언제가 적당한가요?',
          answer: '가정용은 1~2년에 1회, 냉난방 겸용이거나 반려동물을 키우는 집, 아토피 환자가 있는 가정은 매년 봄(사용 전) 청소를 권장합니다.',
        },
        {
          question: '사설 업체와 제조사 공식 서비스 센터 비용 차이는 왜 나나요?',
          answer: '제조사 공식 케어는 본사 엔지니어 규격과 공식 부품 보증이 포함되어 20~30% 더 높으며, 전문 사설 플랫폼 업체는 합리적인 공임과 빠른 일정 조율이 장점입니다.',
        },
      ],
    },
  },
  {
    id: 'service-13',
    number: '13',
    title: '세탁기 분해청소 비용',
    slug: 'washing-machine-cleaning',
    categoryId: 'cleaning',
    categoryName: '청소·가사',
    ruleId: 'rule-washing-machine-cleaning',
    shortDesc: '통돌이 및 드럼 세탁기 스파이더 분해 고압 살균 세척 비용',
    icon: '🧺',
    questions: [
      {
        id: 'washer_type',
        label: '세탁기 종류',
        type: 'select',
        defaultValue: 'drum',
        options: [
          { label: '통돌이 일반 세탁기 (15kg 이하)', value: 'top_small', priceDelta: 70000 },
          { label: '통돌이 대형 세탁기 (16kg 이상)', value: 'top_large', priceDelta: 85000 },
          { label: '드럼 세탁기 (15kg 이하)', value: 'drum_small', priceDelta: 120000 },
          { label: '드럼 세탁기 (16kg 이상 대형)', value: 'drum_large', priceDelta: 140000 },
          { label: '워시타워 / 2in1 일체형 복합기', value: 'washtower', priceDelta: 180000, hint: '건조기 결합 특수 분해' },
        ],
        required: true,
      },
      {
        id: 'contamination_level',
        label: '사용 연수 및 오염 체감',
        type: 'select',
        defaultValue: 'normal',
        options: [
          { label: '구입 1~3년 (정기 관리)', value: 'light', priceDelta: 0 },
          { label: '구입 4~6년 (빨래에 이물질·찌꺼기 발생)', value: 'normal', priceDelta: 10000 },
          { label: '구입 7년 이상 (한 번도 청소 안 함, 악취 극심)', value: 'heavy', priceDelta: 25000 },
        ],
        required: true,
      },
      {
        id: 'dryer_attached',
        label: '건조기 직렬 설치 여부',
        type: 'select',
        defaultValue: 'none',
        options: [
          { label: '단독 설치 (세탁기만 있음)', value: 'none', priceDelta: 0 },
          { label: '건조기 직렬 상단 거치 (내림 작업 필요)', value: 'dryer_down', priceDelta: 30000, hint: '상단 건조기 탈거 및 재설치 공임' },
        ],
        required: true,
      },
    ],
    evidence: {
      provider: '숨고(Soomgo) 세탁기 청소 시세 빅데이터',
      sourceUrl: 'https://soomgo.com/prices/%EC%84%B8%ED%83%81%EA%B8%B0-%EC%B2%AD%EC%86%8C',
      basePrice: 100000,
      minPrice: 70000,
      maxPrice: 220000,
      priceUnit: '대당 70,000원 ~ 220,000원 (통돌이 7~9만, 드럼 11~14만)',
      vatIncluded: true,
      travelFeeIncluded: true,
      materialsIncluded: true,
      surveyedAt: '2026-09-01',
      lastVerifiedAt: '2026-10-09',
      verificationStatus: 'verified',
      reliabilityLevel: 'high',
      sourceType: 'platform_average',
      notes: '숨고 실거래 평균 100,000원(통돌이 최저 70,000원부터 드럼/워시타워 최고 220,000원). 상단 건조기 직렬 거치 해체 시 별도 공임 발생 가능.',
    },
    seo: {
      title: '세탁기 분해청소 비용 견적 계산기 (드럼/통돌이/워시타워) | 바로견적',
      description: '통돌이 세탁기, 드럼 세탁기 완전분해 청소 및 고압 살균 소독 예상비용을 확인하세요.',
      keywords: ['세탁기 청소비용', '드럼세탁기 분해청소', '통돌이 세탁기 청소', '워시타워 청소비', '세탁기 곰팡이 청소'],
      h1: '세탁기 분해청소 비용 계산기',
      canonicalPath: 'https://quote.info-myview.co.kr/estimate/washing-machine-cleaning/',
      faq: [
        {
          question: '세탁조 클리너 약품으로 셀프 청소하면 안 되나요?',
          answer: '세탁조 클리너는 표면의 얕은 때만 녹여내며, 세탁조 바깥쪽과 스파이더(삼발이) 부품 틈새에 굳어붙은 세제 찌꺼기와 곰팡이는 물리적 고압 세척으로만 제거할 수 있습니다.',
        },
        {
          question: '건조기가 세탁기 위에 얹혀져 있는데 청소가 가능한가요?',
          answer: '네, 가능합니다. 다만 상단 건조기를 안전하게 내려놓고 세탁기를 분해해야 하므로 기사 2인 투입 또는 건조기 하차비(3~5만원 선)가 추가될 수 있습니다.',
        },
        {
          question: '청소 후 세탁기 고장 시 A/S 보증을 해주나요?',
          answer: '전문 등록 업체는 작업 전후 정상 작동 시운전을 진행하며, 분해 결합으로 인한 하자 발생 시 통상 1~3개월 무상 A/S 또는 배상 책임 보험을 제공합니다.',
        },
        {
          question: '분해 청소 소요 시간은 얼마나 되나요?',
          answer: '통돌이 세탁기는 약 1시간~1시간 30분, 드럼 세탁기는 구조가 복잡하여 약 2시간~2시간 30분 소요됩니다.',
        },
      ],
    },
  },
  {
    id: 'service-24',
    number: '24',
    title: '곰팡이 제거·방지 시공비',
    slug: 'mold-removal',
    categoryId: 'cleaning',
    categoryName: '청소·가사',
    ruleId: 'rule-mold-removal',
    shortDesc: '베란다, 결로 벽면 곰팡이 뿌리 박멸 및 항균 단열 규조토 코팅 시공비',
    icon: '🦠',
    questions: [
      {
        id: 'space_type',
        label: '시공 공간 유형',
        type: 'select',
        defaultValue: 'veranda',
        options: [
          { label: '베란다 / 발코니 결로 벽면', value: 'veranda', priceDelta: 200000 },
          { label: '방 모서리 / 외벽 쪽 벽지 벽면', value: 'room_wall', priceDelta: 250000 },
          { label: '창문 주변 및 붙박이장 뒤편', value: 'closet_window', priceDelta: 300000 },
          { label: '지하 / 반지하 주택 전체 방', value: 'basement', priceDelta: 500000 },
        ],
        required: true,
      },
      {
        id: 'wall_count',
        label: '오염 벽면 개수',
        type: 'select',
        defaultValue: '1',
        options: [
          { label: '1개 벽면 (부분 시공)', value: '1', priceDelta: 0 },
          { label: '2개 벽면', value: '2', priceDelta: 120000 },
          { label: '3개 벽면 이상 (방 전체 또는 베란다 전체)', value: '3', priceDelta: 240000 },
        ],
        required: true,
      },
      {
        id: 'coating_option',
        label: '방지 시공 범위',
        type: 'select',
        defaultValue: 'coating',
        options: [
          { label: '단순 약품 세척 + 항균 코팅', value: 'basic', priceDelta: 0 },
          { label: '곰팡이 사멸 + 규조토/단열페인트 코팅 (추천)', value: 'coating', priceDelta: 80000 },
          { label: '벽지 철거 + 복합 단열재 시공 + 실크 마감', value: 'insulation', priceDelta: 200000 },
        ],
        required: true,
      },
    ],
    evidence: {
      provider: '숨고(Soomgo) 곰팡이 제거 시세 빅데이터',
      sourceUrl: 'https://soomgo.com/prices/%EA%B3%B0%ED%8C%A1%EC%9D%B4-%EC%A0%9C%EA%B1%B0',
      basePrice: 200000,
      minPrice: 80000,
      maxPrice: 650000,
      priceUnit: '시공건당 80,000원 ~ 650,000원 (단순제거 8만, 단열코팅 20만~35만)',
      vatIncluded: true,
      travelFeeIncluded: true,
      materialsIncluded: true,
      surveyedAt: '2026-09-01',
      lastVerifiedAt: '2026-10-09',
      verificationStatus: 'verified',
      reliabilityLevel: 'high',
      sourceType: 'platform_average',
      notes: '숨고 실거래 평균 200,000원(최저 80,000원, 최고 650,000원). 단열 규조토 코팅 및 벽체 복합 시공 여부에 따라 비용 변동.',
    },
    seo: {
      title: '곰팡이 제거·방지 시공비 견적 계산기 (베란다/벽지/결로) | 바로견적',
      description: '베란다 결로 곰팡이, 방 벽지 곰팡이 제거 및 항균 단열페인트 코팅 시공 예상 견적을 계산해보세요.',
      keywords: ['곰팡이 제거 비용', '베란다 곰팡이 시공비', '결로 곰팡이 방지', '벽지 곰팡이 제거 견적', '단열페인트 시공'],
      h1: '곰팡이 제거·방지 시공비 계산기',
      canonicalPath: 'https://quote.info-myview.co.kr/estimate/mold-removal/',
      faq: [
        {
          question: '락스로 지워도 자꾸 다시 피어나는 이유는 무엇인가요?',
          answer: '락스는 표면의 색소만 표백할 뿐 벽체 내부 콘크리트 포자까지 사멸시키지 못하며, 벽면 온도차로 인한 결로 습기가 남아있으면 1~2주 내에 다시 재발합니다.',
        },
        {
          question: '전문 시공은 어떤 과정으로 진행되나요?',
          answer: '기존 오염물 제거 → 전용 포자 박멸 약품 처리 → 오존 살균 소독 → 항균 프라이머 코팅 → 친환경 단열 규조토/단열재 마감 순으로 진행됩니다.',
        },
        {
          question: '시공 후 재발 방지 보증 기간은 얼마나 되나요?',
          answer: '전문 단열 곰팡이 시공 업체는 통상 1년~2년 무상 A/S 재발 보증서를 발급합니다.',
        },
        {
          question: '벽지를 뜯어내지 않고도 시공할 수 있나요?',
          answer: '벽지 표면에만 살짝 묻은 경우 약품 코팅이 가능하지만, 벽지 안쪽 콘크리트에서 피어난 곰팡이는 반드시 벽지를 제거하고 벽체 원형에 직접 약품 시공해야 합니다.',
        },
      ],
    },
  },
  {
    id: 'service-26',
    number: '26',
    title: '가사도우미 이용비용',
    slug: 'housekeeper-service',
    categoryId: 'cleaning',
    categoryName: '청소·가사',
    ruleId: 'rule-housekeeper-service',
    shortDesc: '정기 및 1회성 가사도우미(파출부) 시간당 이용요금 및 주간 견적',
    icon: '🏡',
    questions: [
      {
        id: 'work_hours',
        label: '1회 이용 시간',
        type: 'select',
        defaultValue: '4',
        options: [
          { label: '2시간 (원룸/소형 특화)', value: '2', priceDelta: 35000 },
          { label: '3시간 (투룸/소형 가구)', value: '3', priceDelta: 48000 },
          { label: '4시간 (가장 일반적인 표준형)', value: '4', priceDelta: 60000 },
          { label: '8시간 (종일 전일제 근무)', value: '8', priceDelta: 110000 },
        ],
        required: true,
      },
      {
        id: 'frequency_type',
        label: '방문 주기',
        type: 'select',
        defaultValue: 'weekly_1',
        options: [
          { label: '1회성 단발 이용', value: 'once', priceDelta: 5000 },
          { label: '주 1회 정기 이용 (월 4회)', value: 'weekly_1', priceDelta: 0 },
          { label: '주 2회 정기 이용 (월 8회)', value: 'weekly_2', priceDelta: -3000, hint: '정기 할인 적용' },
          { label: '주 3회 이상 집중 관리', value: 'weekly_3', priceDelta: -5000 },
        ],
        required: true,
      },
      {
        id: 'scope_level',
        label: '업무 범위',
        type: 'select',
        defaultValue: 'standard',
        options: [
          { label: '기본 가사 (바닥청소 + 설거지 + 쓰레기 배출)', value: 'standard', priceDelta: 0 },
          { label: '가사 + 세탁 및 빨래 개기', value: 'laundry', priceDelta: 5000 },
          { label: '가사 + 간단 밑반찬 조리', value: 'cooking', priceDelta: 15000 },
        ],
        required: true,
      },
    ],
    evidence: {
      provider: '숨고(Soomgo) 가사 도우미 시세 빅데이터',
      sourceUrl: 'https://soomgo.com/prices/%EA%B0%80%EC%82%AC-%EB%8F%84%EC%9A%B0%EB%AF%B8',
      basePrice: 70000,
      minPrice: 20000,
      maxPrice: 200000,
      priceUnit: '회당 55,000원 ~ 70,000원 선 (시간당 15,000원~18,000원)',
      vatIncluded: true,
      travelFeeIncluded: true,
      materialsIncluded: false,
      surveyedAt: '2026-09-01',
      lastVerifiedAt: '2026-10-09',
      verificationStatus: 'verified',
      reliabilityLevel: 'high',
      sourceType: 'platform_average',
      notes: '숨고 실거래 평균 70,000원(최저 20,000원~최고 200,000원). 청소 도구 및 세제는 의뢰인 가정 구비 기준.',
    },
    seo: {
      title: '가사도우미 이용비용 시간당 시세 계산기 | 바로견적',
      description: '가사도우미 2시간, 4시간, 종일제 시간별 요금과 주1회/주2회 정기 이용 월 예상비용을 확인해보세요.',
      keywords: ['가사도우미 비용', '파출부 일당', '가사도우미 시급', '정기 청소도우미', '가사도우미 4시간 비용'],
      h1: '가사도우미 이용비용 계산기',
      canonicalPath: 'https://quote.info-myview.co.kr/estimate/housekeeper-service/',
      faq: [
        {
          question: '청소 도구와 세제는 도우미가 직접 가져오나요?',
          answer: '아닙니다. 가사도우미 서비스는 고객님 가정에 비치된 청소기, 걸레, 세제, 수세미, 쓰레기봉투를 사용하는 것이 원칙입니다.',
        },
        {
          question: '가사도우미가 하지 않는 업무는 무엇인가요?',
          answer: '아이 돌봄(베이비시터), 반려동물 배설물 수거, 외창 닦기, 무거운 가구 재배치, 전자기기 분해 세척 등 위험하거나 전문 영역인 작업은 제외됩니다.',
        },
        {
          question: '집에 사람이 없어도 서비스를 받을 수 있나요?',
          answer: '네. 비밀번호나 열쇠 위치를 사전에 전달하여 비대면으로 서비스를 이용하실 수 있습니다.',
        },
        {
          question: '정기 이용과 1회성 이용의 요금 차이가 있나요?',
          answer: '정기 이용(주 1회 이상) 등록 시 회당 3,000원~5,000원의 할인 혜택이 적용되며 고정 매니저 매칭이 가능합니다.',
        },
      ],
    },
  },
  {
    id: 'service-28',
    number: '28',
    title: '매트리스 전문청소 비용',
    slug: 'mattress-cleaning',
    categoryId: 'cleaning',
    categoryName: '청소·가사',
    ruleId: 'rule-mattress-cleaning',
    shortDesc: '침대 매트리스 집먼지진드기 자외선 건식 청소 및 오줌·얼룩 습식 케어 비용',
    icon: '🛏️',
    questions: [
      {
        id: 'mattress_size',
        label: '매트리스 규격',
        type: 'select',
        defaultValue: 'queen',
        options: [
          { label: '싱글 / 슈퍼싱글 (SS)', value: 'single', priceDelta: 45000 },
          { label: '퀸 (Q)', value: 'queen', priceDelta: 55000 },
          { label: '킹 (K) / 라지킹 (LK)', value: 'king', priceDelta: 65000 },
          { label: '패밀리형 / 모션베드 더블', value: 'family', priceDelta: 85000 },
        ],
        required: true,
      },
      {
        id: 'care_type',
        label: '케어 방식',
        type: 'select',
        defaultValue: 'complex',
        options: [
          { label: '건식 케어만 (진드기·미세먼지·각질 흡입 + UV살균)', value: 'dry', priceDelta: 0 },
          { label: '습식 케어만 (얼룩·오염 스팀 물세척)', value: 'wet', priceDelta: 25000 },
          { label: '건식 + 습식 복합 종합케어 (강력 추천)', value: 'complex', priceDelta: 40000 },
        ],
        required: true,
      },
      {
        id: 'stain_type',
        label: '오염 상태 (습식 선택 시)',
        type: 'select',
        defaultValue: 'normal',
        options: [
          { label: '일반 생활 얼룩 (땀, 피지 찌든때)', value: 'normal', priceDelta: 0 },
          { label: '아이/반려동물 소변·구토 얼룩 및 냄새', value: 'pet_urine', priceDelta: 20000, hint: '친환경 탈취 효소제 투입' },
          { label: '오래 방치된 묵은 혈흔 / 곰팡이 오염', value: 'old_blood', priceDelta: 35000 },
        ],
        required: false,
      },
    ],
    evidence: {
      provider: '숨고(Soomgo) 침대/매트리스 청소 시세 빅데이터',
      sourceUrl: 'https://soomgo.com/prices/%EC%B9%A8%EB%8C%80-%EB%A7%A4%ED%8A%B8%EB%A6%AC%EC%8A%A4-%EC%B2%AD%EC%86%8C',
      basePrice: 80000,
      minPrice: 50000,
      maxPrice: 150000,
      priceUnit: '대당 50,000원 ~ 150,000원 (퀸 건식 5~6만, 습식 종합 8~11만)',
      vatIncluded: true,
      travelFeeIncluded: true,
      materialsIncluded: true,
      surveyedAt: '2026-09-01',
      lastVerifiedAt: '2026-10-09',
      verificationStatus: 'verified',
      reliabilityLevel: 'high',
      sourceType: 'platform_average',
      notes: '숨고 실거래 평균 80,000원(최저 50,000원~최고 150,000원). 양면 케어 및 습식 얼룩 세척 시 건조 시간(6~12시간) 필요.',
    },
    seo: {
      title: '매트리스 청소 비용 견적 계산기 (습식/건식/소변얼룩) | 바로견적',
      description: '침대 매트리스 집먼지진드기 건식 케어 및 반려동물 소변, 커피 얼룩 습식 청소 예상비용을 계산하세요.',
      keywords: ['매트리스 청소비용', '침대 매트리스 청소', '매트리스 소변 얼룩 제거', '매트리스 건식 습식 케어', '침대 진드기 청소'],
      h1: '매트리스 전문청소 비용 계산기',
      canonicalPath: 'https://quote.info-myview.co.kr/estimate/mattress-cleaning/',
      faq: [
        {
          question: '건식 청소와 습식 청소의 차이는 무엇인가요?',
          answer: '건식 청소는 고출력 심층 진동 청소기로 매트리스 내부 30cm 깊이의 진드기 사체, 먼지, 피부 각질을 두드려 빨아들이는 방식이며, 습식 청소는 특수 친환경 세제와 온수로 누적된 땀 얼룩, 소변, 피 얼룩을 물세척 흡입하는 방식입니다.',
        },
        {
          question: '습식 청소를 받으면 침대를 언제부터 사용할 수 있나요?',
          answer: '초강력 흡입 장비로 수분을 90% 이상 탈수하지만, 잔여 습기 건조를 위해 에어컨/선풍기/보일러를 틀고 통상 6~12시간 건조 후 사용하실 수 있습니다.',
        },
        {
          question: '라텍스나 메모리폼 매트리스도 습식 청소가 가능한가요?',
          answer: '천연 라텍스나 고밀도 메모리폼은 열과 수분에 취약하므로 일반 스프링 매트리스와 달리 저온 제한적 습식 또는 건식 전용 케어로 진행되어야 합니다.',
        },
        {
          question: '침대 프레임 청소도 포함되나요?',
          answer: '네. 대부분의 매트리스 전문 케어 서비스에는 헤드보드, 하부 프레임, 침대 주변 먼지 집진 제거가 기본 포함됩니다.',
        },
      ],
    },
  },
  {
    id: 'service-30',
    number: '30',
    title: '사무실 정기청소 비용',
    slug: 'office-cleaning-service',
    categoryId: 'cleaning',
    categoryName: '청소·가사',
    ruleId: 'rule-office-cleaning-service',
    shortDesc: '사업장, 사무실, 병원, 학원 정기 방문 청소 월 관리비용 견적',
    icon: '🏢',
    questions: [
      {
        id: 'office_area',
        label: '사무실 전용면적 (평)',
        type: 'number',
        defaultValue: 30,
        min: 10,
        max: 200,
        step: 5,
        unit: '평',
        helpText: '사업장 전용 실평수를 입력하세요.',
        required: true,
      },
      {
        id: 'frequency_per_week',
        label: '주간 방문 청소 횟수',
        type: 'select',
        defaultValue: '2',
        options: [
          { label: '주 1회 (소규모 스타트업·공방)', value: '1', priceDelta: 100000 },
          { label: '주 2회 (가장 대중적인 가성비 플랜)', value: '2', priceDelta: 180000 },
          { label: '주 3회 (직원 15인 이상 중소기업)', value: '3', priceDelta: 260000 },
          { label: '주 5회 (매일 출근 전 클리닝)', value: '5', priceDelta: 400000 },
        ],
        required: true,
      },
      {
        id: 'scope_option',
        label: '청소 관리 범위',
        type: 'select',
        defaultValue: 'standard',
        options: [
          { label: '기본 (바닥 먼지·물걸레 + 쓰레기통 분리수거)', value: 'basic', priceDelta: 0 },
          { label: '기본 + 내부 단독 화장실 1개소 청소', value: 'standard', priceDelta: 50000 },
          { label: '기본 + 화장실 + 탕비실 싱크대·음식물 집중 관리', value: 'pantry', priceDelta: 80000 },
          { label: '종합 (화장실 + 탕비실 + 회의실 유리 파티션 손자국 제거)', value: 'all', priceDelta: 120000 },
        ],
        required: true,
      },
    ],
    evidence: {
      provider: '숨고(Soomgo) 사무실/상업공간 청소 시세 빅데이터',
      sourceUrl: 'https://soomgo.com/prices/%EC%82%AC%EB%AC%B4%EC%8B%A4-%EC%83%81%EC%97%85%EA%B3%B5%EA%B0%84-%EC%B2%AD%EC%86%8C',
      basePrice: 400000,
      minPrice: 150000,
      maxPrice: 1000000,
      priceUnit: '월정액 기준 150,000원 ~ 1,000,000원 (30평 주2회 기준 월 20만~25만)',
      vatIncluded: true,
      travelFeeIncluded: true,
      materialsIncluded: true,
      surveyedAt: '2026-09-01',
      lastVerifiedAt: '2026-10-09',
      verificationStatus: 'verified',
      reliabilityLevel: 'high',
      sourceType: 'platform_average',
      notes: '숨고 실거래 평균 400,000원(최저 150,000원~최고 1,000,000원). 정기 방문 주간 횟수 및 실평수에 따라 월정액 상이.',
    },
    seo: {
      title: '사무실 정기청소 월비용 견적 계산기 (평수별/주회차별) | 바로견적',
      description: '사무실, 병원, 학원 정기 방문 청소 평수별, 주 1회/2회/3회/5회 방문 횟수별 월 관리 견적을 계산하세요.',
      keywords: ['사무실 청소비용', '사무실 정기청소 견적', '오피스 클리닝 월비용', '학원 청소비', '사무실 청소업체 비용'],
      h1: '사무실 정기청소 월비용 계산기',
      canonicalPath: 'https://quote.info-myview.co.kr/estimate/office-cleaning-service/',
      faq: [
        {
          question: '청소는 근무시간 중에 하나요, 퇴근 후에 하나요?',
          answer: '업무 방해를 최소화하기 위해 통상 퇴근 후 야간(오후 7시~10시) 또는 출근 전 이른 아침(오전 6시~8시)에 청소를 완료합니다.',
        },
        {
          question: '청소용 도구와 세제는 누가 준비하나요?',
          answer: '전문 청소 장비, 약품, 극세사 걸레 등은 청소업체에서 지참하며, 종량제 쓰레기봉투 및 화장지, 물비누 등 화장실 소모품만 사업장에서 구비해 주시면 됩니다.',
        },
        {
          question: '바닥 왁스 코팅이나 카펫 청소도 정기 청소에 포함되나요?',
          answer: '정기 청소는 일상적인 쓸고 닦기 위주이며, 데코타일 기계 박리 왁스 코팅이나 카펫 습식 세척은 연 1~2회 별도 특수 청소 견적으로 진행됩니다.',
        },
        {
          question: '세금계산서 발행이 가능한가요?',
          answer: '네. 정식 위생관리용역 등록 업체는 모두 사업자등록증 및 전자세금계산서 월말 정산 발행이 가능합니다.',
        },
      ],
    },
  },
];
