import type { ServiceDefinition } from '../types';

export const HEATING_COOLING_SERVICES: ServiceDefinition[] = [
  {
    id: 'service-02',
    number: '02',
    title: '에어컨 이전·설치 예상비용',
    slug: 'ac-relocation-installation',
    categoryId: 'heating-cooling',
    categoryName: '냉난방·설비',
    ruleId: 'rule-ac-installation',
    shortDesc: '에어컨 철거, 운반, 재설치, 동배관 연장, 실외기 앵글 및 가스 충전 비용',
    icon: '❄️',
    questions: [
      {
        id: 'ac_type',
        label: '에어컨 종류',
        type: 'select',
        defaultValue: 'stand',
        options: [
          { label: '벽걸이 에어컨', value: 'wall', priceDelta: 130000 },
          { label: '스탠드 에어컨', value: 'stand', priceDelta: 180000, hint: '기본 배관 5m 포함' },
          { label: '2in1 멀티형 (스탠드 1대 + 벽걸이 1대)', value: '2in1', priceDelta: 280000, hint: '배관 2라인 작업' },
        ],
        required: true,
      },
      {
        id: 'pipe_extra_meter',
        label: '추가 배관 길이 (기본 배관 초과분)',
        type: 'select',
        defaultValue: '0',
        options: [
          { label: '기본 배관 내 설치 (추가 없음)', value: '0', priceDelta: 0 },
          { label: '3m 추가 (미터당 약 1.8~2.5만원)', value: '3', priceDelta: 60000 },
          { label: '5m 추가 (실외기 베란다 외부 돌출)', value: '5', priceDelta: 100000 },
          { label: '10m 이상 장거리 배관 매립', value: '10', priceDelta: 200000 },
        ],
        required: true,
      },
      {
        id: 'outdoor_bracket',
        label: '실외기 거치대 (앵글) 상태',
        type: 'select',
        defaultValue: 'built_in',
        options: [
          { label: '실내 실외기실 보유 (앵글 불필요)', value: 'built_in', priceDelta: 0 },
          { label: '기존 앵글 재사용 재설치', value: 'reuse', priceDelta: 30000 },
          { label: '외부 알루미늄 신규 앵글 제작 및 설치', value: 'new_bracket', priceDelta: 120000 },
        ],
        required: true,
      },
      {
        id: 'gas_recharge',
        label: '냉매 가스 충전 및 진공 작업',
        type: 'select',
        defaultValue: 'vacuum_gas',
        options: [
          { label: '기존 냉매 보존 (단순 보충)', value: 'top_up', priceDelta: 30000 },
          { label: '디지털 진공 작업 + R410A 완충 (권장)', value: 'vacuum_gas', priceDelta: 60000 },
        ],
        required: true,
      },
    ],
    evidence: {
      provider: '삼성·LG 공식 설치 기준단가 및 에어컨설치협회 공임표',
      sourceUrl: 'https://soomgo.com/costs/air-conditioner-installation',
      basePrice: 150000,
      priceUnit: '벽걸이 기본 12~15만, 스탠드 16~20만, 2in1 25~32만',
      vatIncluded: true,
      travelFeeIncluded: true,
      materialsIncluded: true,
      surveyedAt: '2026-08-25',
      lastVerifiedAt: '2026-10-01',
      reliabilityLevel: 'high',
      notes: '철거 후 타지역 이동 운반비(3~5만원) 별도. 매립 배관 세척(청관) 필요 시 라인당 5만원 가산.',
    },
    seo: {
      title: '에어컨 이전설치 비용 견적 계산기 (벽걸이/스탠드/배관비용) | 바로견적',
      description: '에어컨 이전설치 기본 공임비, 배관 추가 미터당 단가, 실외기 앵글 제작, 가스 완충 예상비용을 확인하세요.',
      keywords: ['에어컨 이전설치 비용', '에어컨 설치비 견적', '에어컨 배관 추가비용', '2in1 에어컨 설치비', '에어컨 가스충전 비용'],
      h1: '에어컨 이전·설치 예상비용 계산기',
      canonicalPath: 'https://quote.info-myview.co.kr/estimate/ac-relocation-installation/',
      faq: [
        {
          question: '기본 설치비 외에 현장에서 가장 많이 추가되는 항목은 무엇인가요?',
          answer: '배관 추가 길이(미터당 1.8만~2.5만원), 실외기 앵글 제작비(10만~13만원), 배관 매립 아파트의 경우 질소 브로잉 청관 작업비(라인당 5만원)가 대표적입니다.',
        },
        {
          question: '진공 작업은 반드시 해야 하나요?',
          answer: '네. 인버터 에어컨(R410A 친환경 냉매)은 배관 내 수분과 공기를 진공 펌프로 완벽히 빼내지 않으면 냉방 효율이 20% 이상 떨어지고 콤프레셔 수명이 단축됩니다.',
        },
        {
          question: '이사 갈 때 이전 에어컨 철거도 신청해야 하나요?',
          answer: '포장이사 팀에서 기본 철거를 해주기도 하지만, 냉매를 실외기로 모으는 펌프다운 작업을 하지 않고 자르면 가스가 모두 유출되므로 전문 기사의 정석 철거를 권장합니다.',
        },
        {
          question: '설치 후 A/S 보증은 어떻게 되나요?',
          answer: '전문 등록 기사는 냉매 누설 및 배관 결로에 대해 시공일로부터 통상 1~2년 무상 하자보증을 제공합니다.',
        },
      ],
    },
  },
  {
    id: 'service-10',
    number: '10',
    title: '보일러 수리·교체비용',
    slug: 'boiler-repair-replacement',
    categoryId: 'heating-cooling',
    categoryName: '냉난방·설비',
    ruleId: 'rule-boiler-repair-replacement',
    shortDesc: '친환경 콘덴싱 가스보일러 교체 지원금 적용 및 부품 단순 수리 예상비용',
    icon: '🔥',
    questions: [
      {
        id: 'service_type',
        label: '작업 구분',
        type: 'select',
        defaultValue: 'replace_condensing',
        options: [
          { label: '단순 부품 수리 (점화불량/누수/삼방밸브 교체)', value: 'repair_part', priceDelta: 120000, hint: '출장점검비 + 핵심 부품' },
          { label: '전체 신규 교체 (1종 친환경 콘덴싱 가스보일러)', value: 'replace_condensing', priceDelta: 750000, hint: '연통, 가스관, 정부지원금 감안' },
          { label: '전체 신규 교체 (일반 2종 저녹스 보일러)', value: 'replace_normal', priceDelta: 650000, hint: '배수구 없는 구조' },
        ],
        required: true,
      },
      {
        id: 'home_area',
        label: '난방 평형 용량',
        type: 'select',
        defaultValue: 'pyeong_30',
        options: [
          { label: '20평 이하 (14,000~16,000 kcal)', value: 'pyeong_20', priceDelta: -50000 },
          { label: '20~30평형 (18,000~20,000 kcal)', value: 'pyeong_30', priceDelta: 0, hint: '가장 많은 표준 용량' },
          { label: '30~45평형 (22,000~25,000 kcal)', value: 'pyeong_40', priceDelta: 70000 },
          { label: '50평 이상 대형 (30,000 kcal 이상)', value: 'pyeong_50', priceDelta: 150000 },
        ],
        required: true,
      },
      {
        id: 'pipe_flushing_bundle',
        label: '배관 청소 및 부속 교체',
        type: 'select',
        defaultValue: 'bundle',
        options: [
          { label: '기본 교체 (보일러 본체 + 연통 + CO경보기)', value: 'basic', priceDelta: 0 },
          { label: '기본 + 노후 난방배관 녹물 세척 패키지', value: 'bundle', priceDelta: 50000, hint: '난방효율 20% 상승 효과' },
        ],
        required: true,
      },
    ],
    evidence: {
      provider: '귀뚜라미·린나이·경동나비엔 공식 대리점 표준 교체 고시가',
      sourceUrl: 'https://soomgo.com/costs/boiler-replacement',
      basePrice: 700000,
      priceUnit: '30평형 친환경 콘덴싱 교체 75만~90만원 선 (수리 8만~15만)',
      vatIncluded: true,
      travelFeeIncluded: true,
      materialsIncluded: true,
      surveyedAt: '2026-08-30',
      lastVerifiedAt: '2026-10-01',
      reliabilityLevel: 'high',
      notes: '대기관리권역법에 따라 배수구가 있는 보일러실은 친환경 1종 콘덴싱 설치 의무. CO경보기 설치 법적 의무 포함.',
    },
    seo: {
      title: '가스보일러 교체비용 수리 견적 계산기 (경동/린나이/귀뚜라미) | 바로견적',
      description: '친환경 콘덴싱 보일러 평수별 교체비용, 친환경 보조금, 연통 및 CO경보기 포함 실시간 견적을 비교해보세요.',
      keywords: ['보일러 교체비용', '가스보일러 수리비', '친환경 콘덴싱 보일러 가격', '경동나비엔 보일러 교체', '린나이 보일러 가격'],
      h1: '보일러 수리·교체비용 계산기',
      canonicalPath: 'https://quote.info-myview.co.kr/estimate/boiler-repair-replacement/',
      faq: [
        {
          question: '보일러 교체 주기는 몇 년인가요?',
          answer: '한국에너지공단 권장 가스보일러 교체 권장 수명은 10년입니다. 10년이 지나면 열효율이 저하되고 열교환기, 순환펌프 부품 고장이 잦아 수리비보다 교체가 경제적입니다.',
        },
        {
          question: '친환경 콘덴싱 보일러 보조금을 받을 수 있나요?',
          answer: '환경부와 지자체에서 저소득층/취약계층을 대상으로 최대 60만원의 교체 보조금을 지원하며, 일반 가구 지원금은 지자체 예산 소진 여부에 따라 대리점에서 즉시 감면 신청 가능합니다.',
        },
        {
          question: '일산화탄소(CO) 경보기 설치는 필수인가요?',
          answer: '네. 2020년 8월부터 개정된 도시가스사업법에 따라 신규/교체 설치되는 모든 가스보일러실에는 의무적으로 한국소방산업기술원(KFI) 인증 CO경보기를 함께 설치해야 합니다.',
        },
        {
          question: '콘덴싱 보일러를 설치할 수 없는 집도 있나요?',
          answer: '보일러실 내에 응축수를 배출할 배수구(하수구)가 없고 벽을 뚫을 수 없는 구조라면 법적으로 예외 조항인 2종 일반 보일러만 설치 가능합니다.',
        },
      ],
    },
  },
  {
    id: 'service-29',
    number: '29',
    title: '난방·수도배관 청소비용',
    slug: 'heating-pipe-flushing',
    categoryId: 'heating-cooling',
    categoryName: '냉난방·설비',
    ruleId: 'rule-heating-pipe-flushing',
    shortDesc: '보일러 배관 녹물·에어 빼기 편난방 해결 및 수도 녹물 고압 버블 세척비용',
    icon: '♨️',
    questions: [
      {
        id: 'heating_type',
        label: '난방 방식',
        type: 'select',
        defaultValue: 'individual',
        options: [
          { label: '개별 보일러 (가스/기름)', value: 'individual', priceDelta: 120000 },
          { label: '지역난방 / 중앙난방 아파트', value: 'district', priceDelta: 150000, hint: '열교환기 슬러지 고압 배출' },
          { label: '난방배관 + 수돗물 수도배관 동시 세척', value: 'both_pipes', priceDelta: 220000, hint: '계량기부터 수전까지 전수' },
        ],
        required: true,
      },
      {
        id: 'pyeong_size',
        label: '주거 평수',
        type: 'select',
        defaultValue: 'p_25_34',
        options: [
          { label: '20평 이하 (원룸/투룸/소형)', value: 'p_20_under', priceDelta: -20000 },
          { label: '24~34평형 (방 3개 표준형)', value: 'p_25_34', priceDelta: 0 },
          { label: '35~45평형 (방 4개)', value: 'p_35_45', priceDelta: 30000 },
          { label: '50평 이상 대형 주택', value: 'p_50_over', priceDelta: 70000 },
        ],
        required: true,
      },
      {
        id: 'distributor_status',
        label: '난방 분배기 상태',
        type: 'select',
        defaultValue: 'good',
        options: [
          { label: '정상 (밸브 누수 없음)', value: 'good', priceDelta: 0 },
          { label: '분배기 노후 밸브 교체 필요 (누수·부식)', value: 'valve_replace', priceDelta: 60000, hint: '밸브 고착 수리 부품대' },
        ],
        required: false,
      },
    ],
    evidence: {
      provider: '한국난방배관세척협회 및 설비엔지니어 연합 표준공임',
      sourceUrl: 'https://soomgo.com/costs/pipe-cleaning',
      basePrice: 120000,
      priceUnit: '30평 개별난방 12만~16만원, 지역난방 15만~20만원',
      vatIncluded: true,
      travelFeeIncluded: true,
      materialsIncluded: true,
      surveyedAt: '2026-09-02',
      lastVerifiedAt: '2026-10-01',
      reliabilityLevel: 'high',
      notes: '초음파 마이크로버블 파동 장비 투입 기준. 분배기 전체 부식 교체 시 구당 2~3만원 부품비 추가.',
    },
    seo: {
      title: '난방배관 청소 비용 견적 계산기 (보일러 에어빼기/편난방) | 바로견적',
      description: '방 하나만 차가운 편난방 해결, 보일러 난방배관 및 수도 녹물 고압 버블 세척 예상비용을 확인하세요.',
      keywords: ['난방배관 청소비용', '보일러 배관청소', '편난방 해결 비용', '지역난방 배관청소', '수도배관 녹물 청소'],
      h1: '난방·수도배관 청소비용 계산기',
      canonicalPath: 'https://quote.info-myview.co.kr/estimate/heating-pipe-flushing/',
      faq: [
        {
          question: '보일러를 틀어도 특정 방만 차가운 이유는 무엇인가요?',
          answer: '배관 내부에 기포(에어)가 차 있거나, 슬러지(찌꺼기)와 녹물이 배관을 막아 온수 순환이 정체되는 편난방 현상 때문입니다. 배관 세척을 통해 공기와 오염수를 빼내면 균일하게 따뜻해집니다.',
        },
        {
          question: '배관 청소를 하면 가스비가 절약되나요?',
          answer: '네. 배관 내 슬러지가 제거되면 열전도율이 급격히 향상되어 방이 데워지는 시간이 단축되므로 난방비가 통상 15%~25% 절감됩니다.',
        },
        {
          question: '배관 청소 작업 시간은 얼마나 걸리나요?',
          answer: '30평형 아파트 기준 각 분배기 라인별로 오염수를 맑은 물이 나올 때까지 1:1 순환 세척하므로 약 1시간 30분~2시간 30분 소요됩니다.',
        },
        {
          question: '고압 세척 중에 오래된 배관이 터질 위험은 없나요?',
          answer: '전문 장비는 무리한 수압이 아닌 초음파 미세 파동(펄스 공법)으로 이물질만 분리해 내므로 정상 시공 시 배관 파손 위험은 극히 낮습니다.',
        },
      ],
    },
  },
];
