import type { ServiceDefinition } from '../types';

export const INSTALLATION_SERVICES: ServiceDefinition[] = [
  {
    id: 'service-14',
    number: '14',
    title: '디지털 도어락 설치·교체비',
    slug: 'smart-lock-installation',
    categoryId: 'installation',
    categoryName: '생활 설치·교체',
    ruleId: 'rule-smart-lock-installation',
    shortDesc: '현관문 보조키, 주키 일체형, 푸시풀 및 지문인식 도어락 타공 설치비',
    icon: '🔐',
    questions: [
      {
        id: 'lock_type',
        label: '도어락 제품 종류',
        type: 'select',
        defaultValue: 'pushpull',
        options: [
          { label: '보조키형 (손잡이 위에 번호키만 분리 장착)', value: 'rim_lock', priceDelta: 60000 },
          { label: '주키 일체형 (손잡이+도어락 결합형 레버락)', value: 'lever_mortise', priceDelta: 140000 },
          { label: '푸시풀 (Push-Pull 밀고 당기는 프리미엄 도어락)', value: 'pushpull', priceDelta: 240000, hint: '가장 선호도 높은 편리한 모델' },
          { label: '지문인식 + 안면인식 IoT 스마트 도어락', value: 'biometric_iot', priceDelta: 340000 },
        ],
        required: true,
      },
      {
        id: 'supply_mode',
        label: '제품 준비 방식',
        type: 'select',
        defaultValue: 'include_product',
        options: [
          { label: '고객 직접 준비 (자가 구매 제품 단순 출장 설치 공임만)', value: 'labor_only', priceDelta: -100000, hint: '단순 설치 공임 4~6만원' },
          { label: '기사 지참 (정품 새 제품 + 무상 A/S 보증 일체 포함)', value: 'include_product', priceDelta: 0 },
        ],
        required: true,
      },
      {
        id: 'door_plate',
        label: '현관문 보강판 및 타공 필요 여부',
        type: 'select',
        defaultValue: 'need_plate',
        options: [
          { label: '기존 구멍에 바로 호환 (보강판 불필요)', value: 'no_plate', priceDelta: 0 },
          { label: '이전 타공 구멍 가림용 마감 보강판 추가', value: 'need_plate', priceDelta: 20000, hint: '이전 자국 깔끔하게 은폐' },
          { label: '철문 신규 홀쏘 타공 작업 필요', value: 'drill_new', priceDelta: 30000 },
        ],
        required: true,
      },
    ],
    evidence: {
      provider: '숨고(Soomgo) 열쇠/도어락 설치 및 수리 견적 통계',
      sourceUrl: 'https://soomgo.com/prices/%EC%97%B4%EC%87%A0-%EB%8F%84%EC%96%B4%EB%9D%BD-%EC%84%A4%EC%B9%98-%EC%88%98%EB%A6%AC',
      basePrice: 130000,
      minPrice: 45000,
      maxPrice: 320000,
      priceUnit: '시공당 (평균 13만원 / 최저 4.5만 ~ 최고 32만원)',
      vatIncluded: true,
      travelFeeIncluded: true,
      materialsIncluded: true,
      surveyedAt: '2026-10-09',
      lastVerifiedAt: '2026-10-09',
      verificationStatus: 'verified',
      sourceType: 'platform_average',
      reliabilityLevel: 'high',
      notes: '숨고 플랫폼 실거래 데이터 기준. 열쇠/도어락 시공당 평균 13만원 (최저 4.5만원, 최고 32만원). 단순 출장 설치(4.5만~6만원)와 신규 주키/푸시풀 제품 포함 시공에 따라 차이.',
    },
    seo: {
      title: '디지털 도어락 설치 교체비용 견적 계산기 (푸시풀/지문인식/공임) | 바로견적',
      description: '현관문 디지털 도어락 푸시풀 교체비용, 단순 출장 설치 공임, 보강판 타공 견적을 실시간으로 확인해보세요.',
      keywords: ['도어락 설치비용', '도어락 교체비', '푸시풀 도어락 가격', '현관문 번호키 교체', '도어락 공임비'],
      h1: '디지털 도어락 설치·교체비 계산기',
      canonicalPath: 'https://quote.info-myview.co.kr/estimate/smart-lock-installation/',
      faq: [
        {
          question: '인터넷에서 도어락을 샀는데 설치만 맡기면 공임이 얼마인가요?',
          answer: '기존 도어락 탈거 및 신규 제품 단순 설치 공임은 통상 4만~6만원 선이며, 문에 추가 타공이 필요하거나 보강판을 덧대야 할 경우 부속비 1만~2만원이 추가됩니다.',
        },
        {
          question: '보조키형과 주키형의 차이는 무엇인가요?',
          answer: '보조키는 문 손잡이 윗부분에 별도로 열쇠 구멍을 뚫어 장착하는 작은 번호키이며, 주키(모티스)형은 손잡이와 잠금장치가 하나로 일체화되어 문 손잡이를 대체하는 구조입니다.',
        },
        {
          question: '배터리가 방전되어 문이 안 열릴 때는 어떻게 하나요?',
          answer: '편의점에서 사각 9V 건조식 배터리를 구매하여 도어락 실외 측 비상 전원 단자에 접촉시킨 상태에서 비밀번호를 누르면 문을 열 수 있습니다.',
        },
        {
          question: '원룸 전월세 퇴거 시 원상복구를 해야 하나요?',
          answer: '집주인 동의 없이 문을 뚫으면 퇴거 시 변상 문제가 생길 수 있으므로, 타공이 필요 없는 무타공 주키 도어락을 설치하고 기존 손잡이를 보관해 두는 것을 권장합니다.',
        },
      ],
    },
  },
  {
    id: 'service-16',
    number: '16',
    title: '벽걸이 TV 설치비용',
    slug: 'wall-mounted-tv-installation',
    categoryId: 'installation',
    categoryName: '생활 설치·교체',
    ruleId: 'rule-wall-mounted-tv-installation',
    shortDesc: '아트월 대리석·타일 무타공 및 타공 벽걸이 TV 설치, 셋톱박스 선 매립',
    icon: '📺',
    questions: [
      {
        id: 'tv_size',
        label: 'TV 화면 크기 (인치)',
        type: 'select',
        defaultValue: 'inch_65_75',
        options: [
          { label: '43인치 ~ 55인치 (중소형)', value: 'inch_43_55', priceDelta: 60000 },
          { label: '65인치 ~ 75인치 (국민 대형 TV 표준)', value: 'inch_65_75', priceDelta: 90000, hint: '가장 많은 설치 규격' },
          { label: '85인치 이상 ~ 98인치 초대형 거포', value: 'inch_85_over', priceDelta: 150000, hint: '기사 2인 의무 투입' },
        ],
        required: true,
      },
      {
        id: 'wall_material',
        label: '벽면 자재 환경',
        type: 'select',
        defaultValue: 'tile_artwall',
        options: [
          { label: '콘크리트 일반 벽 (시멘트 타공)', value: 'concrete', priceDelta: 0 },
          { label: '석고보드 가벽 (보강목 프레임 체결)', value: 'drywall', priceDelta: 20000 },
          { label: '타일 / 대리석 / 아트월 (다이아몬드 특수 타공 깨짐방지)', value: 'tile_artwall', priceDelta: 30000 },
          { label: '벽면 무타공 시공 (콘센트 브래킷 지지대 방식, 전월세 추천)', value: 'no_drill', priceDelta: 150000, hint: '구멍 0개로 거치' },
        ],
        required: true,
      },
      {
        id: 'bracket_type',
        label: '브래킷 및 주변기기 매립',
        type: 'select',
        defaultValue: 'swivel_wire_hide',
        options: [
          { label: '고정형 브래킷 + 단순 거치 (선 노출 몰딩)', value: 'fixed_molding', priceDelta: 20000 },
          { label: '상하좌우 관절형 브래킷 + 셋톱박스·공유기 숨김', value: 'swivel_wire_hide', priceDelta: 60000 },
          { label: '상하좌우 회전 정품 브래킷 + 셋톱/공유기/사운드바 풀 매립 선없는TV', value: 'full_hidden', priceDelta: 100000, hint: '전선 매립 콘센트 작업 일체' },
        ],
        required: true,
      },
    ],
    evidence: {
      provider: '숨고(Soomgo) 벽걸이TV 설치 및 철거 견적 통계',
      sourceUrl: 'https://soomgo.com/prices/%EB%B2%BD%EA%B1%B8%EC%9D%B4TV-%EC%84%A4%EC%B9%98-%EC%B2%A0%EA%B1%B0',
      basePrice: 110000,
      minPrice: 50000,
      maxPrice: 265000,
      priceUnit: '시공당 (평균 11만원 / 최저 5만 ~ 최고 26.5만원)',
      vatIncluded: true,
      travelFeeIncluded: true,
      materialsIncluded: true,
      surveyedAt: '2026-10-09',
      lastVerifiedAt: '2026-10-09',
      verificationStatus: 'verified',
      sourceType: 'platform_average',
      reliabilityLevel: 'high',
      notes: '숨고 플랫폼 실거래 데이터 기준. 벽걸이TV 설치 및 철거 평균 11만원 (최저 5만원, 최고 26.5만원). TV 크기(65/75/85인치), 대리석 타공 여부 및 무타공 공법에 따라 상이.',
    },
    seo: {
      title: '벽걸이 TV 설치비용 선없는TV 견적 계산기 (무타공/대리석/인치별) | 바로견적',
      description: '65인치, 75인치, 85인치 벽걸이 TV 설치비용, 대리석 아트월 특수 타공, 무타공 벽걸이 TV 및 셋톱박스 선 매립 견적을 확인하세요.',
      keywords: ['벽걸이 TV 설치비용', '무타공 벽걸이 TV 가격', '75인치 벽걸이 TV 설치비', '셋톱박스 숨기기 비용', '대리석 벽걸이 TV 타공'],
      h1: '벽걸이 TV 설치비용 계산기',
      canonicalPath: 'https://quote.info-myview.co.kr/estimate/wall-mounted-tv-installation/',
      faq: [
        {
          question: '무타공 벽걸이 TV는 어떻게 구멍 없이 벽에 고정되나요?',
          answer: '벽 중앙의 콘센트 단자함을 열어 벽체 내부 콘크리트 박스 프레임에 특수 고강도 지지대 앵커를 결합한 후 지렛대 원리로 TV 하중(100kg 이상)을 견디는 특허 공법입니다. 퇴거 시 원상복구가 100% 가능합니다.',
        },
        {
          question: '대리석이나 폴리싱 타일에 구멍을 뚫다가 깨지지 않나요?',
          answer: '전문 기사는 진동을 주는 해머드릴이 아닌 수냉식 다이아몬드 코어 비트 회전 드릴을 사용하므로 타일 크랙 없이 안전하게 12mm 정밀 타공합니다.',
        },
        {
          question: '셋톱박스와 와이파이 공유기, 전원선은 어디로 숨겨지나요?',
          answer: 'TV 뒷면에 전용 브래킷으로 셋톱박스와 공유기를 거치하고, 벽 안쪽으로 동축케이블과 전기선을 매립하여 겉으로 전선이 하나도 보이지 않는 "선 없는 TV"를 완성합니다.',
        },
        {
          question: 'TV 브래킷은 제조사 정품을 사야 하나요?',
          answer: '제조사 정품 브래킷은 8만~12만원으로 비싸지만 유격이 적고 부드러우며, 국내 인증 호환 관절형 브래킷(3만~5만원)도 안전 하중 검증을 통과하여 널리 사용됩니다.',
        },
      ],
    },
  },
  {
    id: 'service-17',
    number: '17',
    title: 'LED 조명 설치·교체비용',
    slug: 'lighting-installation',
    categoryId: 'installation',
    categoryName: '생활 설치·교체',
    ruleId: 'rule-lighting-installation',
    shortDesc: '거실등, 방등, 주방등 LED 교체, 식탁 팬던트등, 매립등(다운라이트) 타공 시공비',
    icon: '💡',
    questions: [
      {
        id: 'lighting_scope',
        label: '설치 조명 수량 및 범위',
        type: 'select',
        defaultValue: 'living_room_main',
        options: [
          { label: '단품 1~2개소 (방등 1개 또는 식탁 팬던트등 교체)', value: 'single_room', priceDelta: 40000 },
          { label: '거실 대형 메인 LED 조명 (3~4등 일체형)', value: 'living_room_main', priceDelta: 60000 },
          { label: '가정집 전체 LED 일괄 교체 (거실+방3+주방+욕실2)', value: 'whole_home', priceDelta: 200000, hint: '전체 조명 리모델링 패키지' },
          { label: '3인치 다운라이트 / COB 매립등 타공 배선 시공 (10개소)', value: 'downlight_10', priceDelta: 250000, hint: '천장 타공 + 전기 입선' },
        ],
        required: true,
      },
      {
        id: 'product_supply',
        label: '조명 등기구 준비 방식',
        type: 'select',
        defaultValue: 'labor_only',
        options: [
          { label: '고객 직접 준비 (단순 교체 출장 공임만)', value: 'labor_only', priceDelta: 0, hint: '인터넷 구매품 교체' },
          { label: '기사 지참 (LG/삼성 이노텍 플리커프리 고효율 LED 제품 포함)', value: 'with_fixtures', priceDelta: 150000, hint: '무상 A/S 2년 보증' },
        ],
        required: true,
      },
      {
        id: 'switch_outlet_bundle',
        label: '스위치 / 콘센트 커버 전면 교체 추가',
        type: 'select',
        defaultValue: 'none',
        options: [
          { label: '조명만 시공', value: 'none', priceDelta: 0 },
          { label: '집 전체 스위치 + 나노/르그랑 콘센트 15개소 교체 패키지', value: 'switch_bundle', priceDelta: 100000, hint: '황변 노후 스위치 일괄 신품 교체' },
        ],
        required: false,
      },
    ],
    evidence: {
      provider: '숨고(Soomgo) 조명 인테리어 견적 통계',
      sourceUrl: 'https://soomgo.com/prices/%EC%A1%B0%EB%AA%85-%EC%9D%B8%ED%85%8C%EB%A6%AC%EC%96%B4',
      basePrice: 250000,
      minPrice: 40000,
      maxPrice: 1100000,
      priceUnit: '시공당 (평균 25만원 / 최저 4만 ~ 최고 110만원)',
      vatIncluded: true,
      travelFeeIncluded: true,
      materialsIncluded: true,
      surveyedAt: '2026-10-09',
      lastVerifiedAt: '2026-10-09',
      verificationStatus: 'verified',
      sourceType: 'platform_average',
      reliabilityLevel: 'high',
      notes: '숨고 플랫폼 실거래 데이터 기준. 조명 인테리어 시공 평균 25만원 (최저 4만원, 최고 110만원). 단품 단순 교체(4만~6만원)와 가정집 전체 LED 일괄 교체 및 다운라이트 매립등 시공에 따라 차이.',
    },
    seo: {
      title: 'LED 조명 설치비용 교체 공임 견적 계산기 (거실등/방등/매립등) | 바로견적',
      description: '거실 LED등 교체비용, 방등 식탁등 교체 출장 공임, 다운라이트 매립등 타공 및 스위치 콘센트 교체 견적을 계산하세요.',
      keywords: ['LED 조명 교체비용', '거실등 교체 공임', '방등 교체비', '조명 설치 출장비', '매립등 다운라이트 시공비'],
      h1: 'LED 조명 설치·교체비용 계산기',
      canonicalPath: 'https://quote.info-myview.co.kr/estimate/lighting-installation/',
      faq: [
        {
          question: '직접 산 조명을 달아주는 단순 공임 출장비는 얼마인가요?',
          answer: '단품 1개 출장 시 기본 출장공임은 4만~5만원이며, 3~4개 이상 여러 개를 한 번에 교체할 경우 개당 2만~3만원 꼴로 저렴해집니다.',
        },
        {
          question: '플리커 프리(Flicker-Free) LED 조명이 왜 중요한가요?',
          answer: '육안으로는 보이지 않지만 스마트폰 카메라로 비췄을 때 검은 줄이 생기는 미세 깜빡임 현상을 플리커라고 합니다. 플리커 프리 인증 LED는 눈의 피로와 시력 저하, 두통을 예방합니다.',
        },
        {
          question: '기존 등기구와 크기가 달라서 천장에 구멍이나 벽지 자국이 보이면 어떻게 하나요?',
          answer: '기존 등기구를 떼어낸 자리가 노출될 수 있으므로 기존 등보다 조금 더 크거나 동일한 규격의 슬림 평판 엣지등을 구매하시거나, 천장 도배 전에 교체하시는 것이 가장 좋습니다.',
        },
        {
          question: '기존 형광등 폐기물도 수거해 주시나요?',
          answer: '유리관 형광등은 아파트 분리수거함에 배출해야 하지만, 떼어낸 고철 철제 등기구 프레임은 기사님이 무상으로 수거해 드립니다.',
        },
      ],
    },
  },
  {
    id: 'service-27',
    number: '27',
    title: '주방후드 설치·교체비용',
    slug: 'kitchen-hood-replacement',
    categoryId: 'installation',
    categoryName: '생활 설치·교체',
    ruleId: 'rule-kitchen-hood-replacement',
    shortDesc: '싱크대 상부장 슬라이딩 후드, 스테인리스 통후드, 침니후드 교체 및 자바라 배관 시공',
    icon: '🍳',
    questions: [
      {
        id: 'hood_type',
        label: '주방후드 기종 형태',
        type: 'select',
        defaultValue: 'built_in_slider',
        options: [
          { label: '슬라이딩 슬림형 (잡아당기면 켜지는 상부장 매립형)', value: 'built_in_slider', priceDelta: 90000, hint: '원룸/20평형대 대중적 모델' },
          { label: '통후드 (가로 60cm 전면 스테인리스/블랙)', value: 'box_hood', priceDelta: 160000, hint: '흡입력 우수한 단독형' },
          { label: '침니형 (가로 90cm 굴뚝 모양 와이드 고급형)', value: 'chimney', priceDelta: 250000 },
          { label: '단순 출장 설치 공임만 (고객 자가 구매 제품)', value: 'labor_only', priceDelta: 50000 },
        ],
        required: true,
      },
      {
        id: 'duct_replace',
        label: '알루미늄 배기 자바라 덕트 교체',
        type: 'select',
        defaultValue: 'duct_new',
        options: [
          { label: '기존 자바라 재사용', value: 'reuse', priceDelta: 0 },
          { label: '새 단열 난연 알루미늄 자바라 관 교체 (기름때 악취 방지)', value: 'duct_new', priceDelta: 20000, hint: '역류 방지 댐퍼 점검 포함' },
        ],
        required: true,
      },
      {
        id: 'fire_extinguisher',
        label: '자동식 소화기 이전 장착 여부',
        type: 'select',
        defaultValue: 'none',
        options: [
          { label: '소화기 없음 (일반 주택)', value: 'none', priceDelta: 0 },
          { label: '기존 자동확산 주방 소화기 노즐/센서 안전 이전 설치', value: 'extinguisher_transfer', priceDelta: 40000, hint: '아파트 법적 소방시설 유지 필수' },
        ],
        required: true,
      },
    ],
    evidence: {
      provider: '숨고(Soomgo) 주방 후드 설치 및 교체 견적 통계',
      sourceUrl: 'https://soomgo.com/prices/%EC%A3%BC%EB%B0%A9%ED%9B%84%EB%93%9C-%EA%B5%90%EC%B2%B4-%EC%84%A4%EC%B9%98',
      basePrice: 230000,
      minPrice: 80000,
      maxPrice: 450000,
      priceUnit: '건당 (평균 23만원 / 최저 8만 ~ 최고 45만원)',
      vatIncluded: true,
      travelFeeIncluded: true,
      materialsIncluded: true,
      surveyedAt: '2026-10-09',
      lastVerifiedAt: '2026-10-09',
      verificationStatus: 'verified',
      sourceType: 'platform_average',
      reliabilityLevel: 'high',
      notes: '숨고 플랫폼 실거래 데이터 기준. 주방 후드 설치 및 교체 평균 23만원 (최저 8만원, 최고 45만원). 후드 기종(슬라이딩/통후드/침니형) 및 자바라 덕트 교체 여부에 따라 상이.',
    },
    seo: {
      title: '주방 싱크대 후드 교체비용 견적 계산기 (슬라이딩/통후드/하츠) | 바로견적',
      description: '하츠 주방후드 슬라이딩 렌지후드 교체비용, 가로 60cm 통후드, 자바라 배관 교체 및 자동식소화기 이전 설치 견적을 확인하세요.',
      keywords: ['주방후드 교체비용', '렌지후드 교체 가격', '하츠 주방후드 교체', '슬라이딩 후드 가격', '주방후드 소화기 이전'],
      h1: '주방후드 설치·교체비용 계산기',
      canonicalPath: 'https://quote.info-myview.co.kr/estimate/kitchen-hood-replacement/',
      faq: [
        {
          question: '주방후드 교체 주기는 얼마나 되나요?',
          answer: '후드 내부 모터와 팬에 끈적한 기름때가 찌들면 흡입력이 반토막 나고 화재 위험이 높아집니다. 통상 5~7년 주기로 모터 세트 교체를 권장합니다.',
        },
        {
          question: '아파트 후드 안쪽에 있는 빨간색 쇠뭉치는 무엇인가요?',
          answer: '소방법상 의무 설치된 "주방 자동식 소화기" 장치입니다. 후드 교체 시 온도 센서와 가스 차단 노즐을 새 후드에 정밀 이식 장착해야 화재 감지 경보가 정상 작동합니다.',
        },
        {
          question: '요리할 때 다른 집 음식 냄새가 역류해 들어오는 것은 왜 그런가요?',
          answer: '아파트 공동 환기구를 타고 냄새가 역류하는 현상입니다. 냄새를 막으려면 후드 자바라에 전동 댐퍼(전기 개폐식 밸브, 약 5만~7만원)를 함께 설치하시면 100% 차단됩니다.',
        },
        {
          question: '기존 고장난 후드도 수거해 가나요?',
          answer: '네. 교체 후 탈거된 기름때 찌든 헌 후드는 기사님이 박스에 담아 무상으로 수거 폐기해 드립니다.',
        },
      ],
    },
  },
];
