import type { ServiceDefinition } from '../types';

export const INTERIOR_SERVICES: ServiceDefinition[] = [
  {
    id: 'service-06',
    number: '06',
    title: '도배·장판 시공비용',
    slug: 'wallpaper-flooring',
    categoryId: 'interior',
    categoryName: '인테리어·시공',
    ruleId: 'rule-wallpaper-flooring',
    shortDesc: '아파트, 빌라 광폭합지·실크벽지 도배 및 모노륨 장판 평당 시공 견적',
    icon: '🏠',
    questions: [
      {
        id: 'home_pyeong',
        label: '공급면적 (평형)',
        type: 'number',
        defaultValue: 24,
        min: 6,
        max: 60,
        step: 1,
        unit: '평',
        helpText: '주거지 분양 공급평수를 입력하세요.',
        required: true,
      },
      {
        id: 'wallpaper_type',
        label: '벽지 종류',
        type: 'select',
        defaultValue: 'silk_all',
        options: [
          { label: '광폭합지 전체 (가성비·전월세 추천)', value: 'paper_all', priceDelta: 700000 },
          { label: '거실 실크 + 방 합지 (대중적인 절충형)', value: 'silk_living_paper_room', priceDelta: 1050000 },
          { label: '실크벽지 전체 (고급 마감, 내구성 우수)', value: 'silk_all', priceDelta: 1350000, hint: '부직포 띄움 시공 포함' },
        ],
        required: true,
      },
      {
        id: 'flooring_type',
        label: '바닥재 시공 여부 및 종류',
        type: 'select',
        defaultValue: 'monoleum_2_2',
        options: [
          { label: '바닥재 시공 안 함 (도배만 진행)', value: 'none', priceDelta: 0 },
          { label: '모노륨 장판 1.8T (원룸/임대용 표준)', value: 'monoleum_1_8', priceDelta: 500000 },
          { label: '모노륨 장판 2.2T (가정용 추천 표준)', value: 'monoleum_2_2', priceDelta: 650000 },
          { label: '친환경 강마루 시공 (철거·걸레받이 포함)', value: 'hardwood', priceDelta: 1600000 },
        ],
        required: true,
      },
      {
        id: 'occupied_status',
        label: '거주 상태 (짐 유무)',
        type: 'select',
        defaultValue: 'empty',
        options: [
          { label: '빈 집 (공실 상태 시공)', value: 'empty', priceDelta: 0 },
          { label: '살고 있는 집 (가구·짐 보양 및 이동 인건비)', value: 'occupied', priceDelta: 300000, hint: '짐 옮기며 작업하는 추가 공임' },
        ],
        required: true,
      },
    ],
    evidence: {
      provider: '숨고(Soomgo) 도배장판 시공 견적 통계',
      sourceUrl: 'https://soomgo.com/prices/%EB%8F%84%EB%B0%B0-%EC%9E%A5%ED%8C%90-%EC%8B%9C%EA%B3%B5',
      basePrice: 1200000,
      minPrice: 250000,
      maxPrice: 2700000,
      priceUnit: '건당 (평균 120만원 / 최저 25만 ~ 최고 270만원)',
      vatIncluded: true,
      travelFeeIncluded: true,
      materialsIncluded: true,
      surveyedAt: '2026-10-09',
      lastVerifiedAt: '2026-10-09',
      verificationStatus: 'verified',
      sourceType: 'platform_average',
      reliabilityLevel: 'high',
      notes: '숨고 플랫폼 실거래 데이터 기준. 도배장판 시공 평균 120만원 (최저 25만원, 최고 270만원). 현장 평수 및 벽지 종류(실크/합지)에 따라 변동.',
    },
    seo: {
      title: '도배 장판 시공비용 견적 계산기 (실크/합지/평수별) | 바로견적',
      description: '24평, 32평 아파트 도배 장판 평당 가격, 실크벽지 합지벽지 비용 차이, 짐 있는 집 추가 공임을 계산해보세요.',
      keywords: ['도배 장판 비용', '아파트 도배 견적', '실크벽지 도배비용', '24평 도배장판', '32평 도배비용'],
      h1: '도배·장판 시공비용 계산기',
      canonicalPath: 'https://quote.info-myview.co.kr/estimate/wallpaper-flooring/',
      faq: [
        {
          question: '합지와 실크벽지의 가장 큰 장단점 차이는 무엇인가요?',
          answer: '합지는 종이 재질로 친환경적이고 시공비가 30% 저렴하지만 오염에 약하고 이음매가 보입니다. 실크벽지는 PVC 코팅으로 물걸레 청소가 가능하고 부직포 띄움 시공으로 벽면이 매끈하지만 자재비와 인건비가 높습니다.',
        },
        {
          question: '살고 있는 집 도배 시 비용이 왜 더 비싼가요?',
          answer: '무거운 냉장고, 장롱, 침대를 보양하고 방마다 짐을 옮겨가며 작업해야 하므로 도배사 1~2인이 추가 투입되어 짐 이동 품삯(20만~35만원)이 발생합니다.',
        },
        {
          question: '시공 당일 벽지가 쭈글쭈글해 보이는 것은 하자벽지인가요?',
          answer: '아닙니다. 도배 풀이 마르지 않아 젖어 있는 상태이므로 창문을 닫고 2~3일간 자연 건조하면 벽지가 팽팽하게 펴집니다. 보일러를 세게 틀면 이음매가 터질 수 있으니 주의하세요.',
        },
        {
          question: '기존 벽지를 다 뜯어내고 작업하나요?',
          answer: '실크벽지는 겉면 비닐을 반드시 제거하고 부직포 초배를 새로 하며, 합지벽지는 상태가 양호하면 덧방도 가능하지만 들뜸 방지를 위해 기본 철거 후 시공을 권장합니다.',
        },
      ],
    },
  },
  {
    id: 'service-09',
    number: '09',
    title: '욕실 리모델링 비용',
    slug: 'bathroom-renovation',
    categoryId: 'interior',
    categoryName: '인테리어·시공',
    ruleId: 'rule-bathroom-renovation',
    shortDesc: '화장실 타일 덧방·철거방수, 위생도기, 수전, 젠다이, 천장재 일체 리모델링',
    icon: '🛁',
    questions: [
      {
        id: 'construction_method',
        label: '공사 방식',
        type: 'select',
        defaultValue: 'overlay',
        options: [
          { label: '타일 덧방 시공 (기존 타일 위에 본드 부착, 가성비 최고)', value: 'overlay', priceDelta: 2200000, hint: '누수 없고 타일 튼튼한 욕실' },
          { label: '올철거 + 3차 액체방수 (누수 해결, 신축급 복원)', value: 'full_waterproof', priceDelta: 3300000, hint: 'UBC UBR욕실이나 누수 있는 화장실' },
        ],
        required: true,
      },
      {
        id: 'fixtures_grade',
        label: '도기 및 수전 자재 등급',
        type: 'select',
        defaultValue: 'standard',
        options: [
          { label: '실속형 (중소기업 KS 인증 치마형 양변기/세면대)', value: 'economic', priceDelta: -200000 },
          { label: '표준형 (대림바스 / 이누스 브랜드 위생도기 세트)', value: 'standard', priceDelta: 0, hint: '가장 만족도 높은 대중적 등급' },
          { label: '고급형 (아메리칸스탠다드 무광 수전 + 졸리컷 타일 마감)', value: 'premium', priceDelta: 600000 },
        ],
        required: true,
      },
      {
        id: 'layout_option',
        label: '샤워 공간 옵션',
        type: 'select',
        defaultValue: 'partition',
        options: [
          { label: '유리 샤워 파티션 설치', value: 'partition', priceDelta: 150000 },
          { label: '아크릴 욕조 신규 시공', value: 'bathtub', priceDelta: 350000 },
          { label: '옵션 없음 (오픈형 심플 샤워 공간)', value: 'none', priceDelta: 0 },
        ],
        required: true,
      },
    ],
    evidence: {
      provider: '숨고(Soomgo) 욕실/화장실 리모델링 견적 통계',
      sourceUrl: 'https://soomgo.com/prices/%EC%9A%95%EC%8B%A4-%EB%A6%AC%EB%AA%A8%EB%8D%B8%EB%A7%81',
      basePrice: 1780000,
      minPrice: 150000,
      maxPrice: 3800000,
      priceUnit: '건당 (평균 178만원 / 최저 15만 ~ 최고 380만원)',
      vatIncluded: true,
      travelFeeIncluded: true,
      materialsIncluded: true,
      surveyedAt: '2026-10-09',
      lastVerifiedAt: '2026-10-09',
      verificationStatus: 'verified',
      sourceType: 'platform_average',
      reliabilityLevel: 'high',
      notes: '숨고 플랫폼 실거래 데이터 기준. 욕실/화장실 리모델링 평균 178만원 (최저 15만원, 최고 380만원). 덧방 시공과 올철거 방수 여부에 따라 차이.',
    },
    seo: {
      title: '화장실 욕실 리모델링 비용 견적 계산기 (덧방/올철거/대림바스) | 바로견적',
      description: '욕실 화장실 타일 덧방 공사, 올철거 방수 시공비용, 대림바스 도기 세트 포함 실시간 공사 견적을 산출해보세요.',
      keywords: ['욕실 리모델링 비용', '화장실 공사비용', '욕실 덧방 비용', '화장실 올철거 방수비용', '대림바스 욕실 견적'],
      h1: '욕실 리모델링 비용 계산기',
      canonicalPath: 'https://quote.info-myview.co.kr/estimate/bathroom-renovation/',
      faq: [
        {
          question: '타일 덧방 시공과 올철거 방수 시공의 기준은 무엇인가요?',
          answer: '기존 타일을 두드렸을 때 텅 빈 소리가 나거나 들뜬 곳이 없고 아랫집 누수가 없다면 덧방(공사기간 2~3일, 200만원대)이 경제적입니다. 반면 타일 탈락이 심하거나 UBR 욕실(플라스틱 조립형), 누수가 있다면 올철거 방수(공사기간 4~5일, 300만원대)를 진행해야 합니다.',
        },
        {
          question: '공사 기간 동안 화장실을 아예 쓸 수 없나요?',
          answer: '네. 타일 압착 시멘트와 방수액, 메지가 양생되는 최소 48시간 동안은 양변기와 물 사용이 불가능하므로 거실 화장실과 안방 화장실을 순차 공사하거나 외부 화장실을 이용해야 합니다.',
        },
        {
          question: '젠다이(조적 선반) 시공은 꼭 해야 하나요?',
          answer: '세면대 위에 슬라이딩 거울장을 설치할 경우, 젠다이가 없으면 세수할 때 머리를 부딪힐 수 있어 배관을 연장하고 벽돌을 쌓는 젠다이 조적 시공을 적극 권장합니다.',
        },
        {
          question: '욕조를 없애고 샤워 파티션으로 바꾸면 방수 공사가 필요한가요?',
          answer: '욕조를 들어낸 자리는 바닥 콘크리트가 노출되므로, 해당 부분에 철저한 2~3차 방수 미장을 한 뒤 바닥 타일을 마감해야 누수가 생기지 않습니다.',
        },
      ],
    },
  },
  {
    id: 'service-15',
    number: '15',
    title: '싱크대·주방가구 교체비용',
    slug: 'kitchen-cabinet-replacement',
    categoryId: 'interior',
    categoryName: '인테리어·시공',
    ruleId: 'rule-kitchen-cabinet-replacement',
    shortDesc: '일자형, ㄱ자형 싱크대 맞춤 제작, 인조대리석 상판, 침니후드, 철거 수거 포함',
    icon: '🍽️',
    questions: [
      {
        id: 'layout_type',
        label: '싱크대 형태 및 길이',
        type: 'select',
        defaultValue: 'straight_2_4m',
        options: [
          { label: '일자형 2.4m 이하 (원룸/소형 투룸)', value: 'straight_2_4m', priceDelta: 1400000 },
          { label: '일자형 3.0m (24평형 표준 아파트)', value: 'straight_3_0m', priceDelta: 1800000 },
          { label: 'ㄱ자형 3.5m (코너형 수납 강화)', value: 'l_shape_3_5m', priceDelta: 2400000, hint: '코너 회전 수납장' },
          { label: 'ㄷ자형 아일랜드 식탁 결합형 (34평 이상)', value: 'u_shape_island', priceDelta: 3300000 },
        ],
        required: true,
      },
      {
        id: 'countertop_material',
        label: '상판 자재 종류',
        type: 'select',
        defaultValue: 'solid_surface',
        options: [
          { label: '기본 국산 인조대리석 (LG 하이막스 / 롯데 스타론 12T)', value: 'solid_surface', priceDelta: 0 },
          { label: '프리미엄 엔지니어드스톤 (칸스톤 칸타빌레)', value: 'engineered_stone', priceDelta: 500000, hint: '스크래치 및 열에 탁월' },
          { label: '최고급 세라믹 상판 (12T 무광 대형 슬랩)', value: 'ceramic', priceDelta: 1000000 },
        ],
        required: true,
      },
      {
        id: 'door_finish',
        label: '도어 표면 마감재',
        type: 'select',
        defaultValue: 'pet_matt',
        options: [
          { label: '친환경 E0 무광 PET (가장 트렌디한 무광 백색/크림)', value: 'pet_matt', priceDelta: 0 },
          { label: 'UV 하이그로시 유광 (청소 용이)', value: 'high_glossy', priceDelta: -50000 },
          { label: '우레탄 도장 도어 (웨인스코팅 프레임)', value: 'lacquer', priceDelta: 400000 },
        ],
        required: true,
      },
    ],
    evidence: {
      provider: '숨고(Soomgo) 싱크대 교체 견적 통계',
      sourceUrl: 'https://soomgo.com/prices/%EC%8B%B1%ED%81%AC%EB%8C%80-%EA%B5%90%EC%B2%B4',
      basePrice: 800000,
      minPrice: 150000,
      maxPrice: 3000000,
      priceUnit: '건당 (평균 80만원 / 최저 15만 ~ 최고 300만원)',
      vatIncluded: true,
      travelFeeIncluded: true,
      materialsIncluded: true,
      surveyedAt: '2026-10-09',
      lastVerifiedAt: '2026-10-09',
      verificationStatus: 'verified',
      sourceType: 'platform_average',
      reliabilityLevel: 'high',
      notes: '숨고 플랫폼 실거래 데이터 기준. 싱크대 교체 공사 평균 80만원 (최저 15만원, 최고 300만원). 형태(일자형/ㄱ자형/ㄷ자형) 및 상판 재질에 따라 변동.',
    },
    seo: {
      title: '싱크대 교체비용 주방 리모델링 견적 계산기 (일자/ㄱ자/인조대리석) | 바로견적',
      description: '아파트 싱크대 교체 평형별 길이, 인조대리석 칸스톤 상판, PET 무광도어 맞춤 제작 예상가격을 확인하세요.',
      keywords: ['싱크대 교체비용', '주방 싱크대 견적', '싱크대 맞춤 가격', 'ㄱ자 싱크대 가격', '인조대리석 싱크대 교체'],
      h1: '싱크대·주방가구 교체비용 계산기',
      canonicalPath: 'https://quote.info-myview.co.kr/estimate/kitchen-cabinet-replacement/',
      faq: [
        {
          question: '사제 맞춤 싱크대와 브랜드 싱크대(한샘, 리바트)의 품질 차이는 큰가요?',
          answer: '도어 E0 친환경 등급 자재, 블룸(Blum) 또는 하페레 하드웨어 댐퍼 힌지, 동일한 LX/롯데 인조대리석 상판을 쓴다면 사제 공장 직영 제작이 브랜드 대비 30~40% 저렴하면서도 동등한 내구성을 제공합니다.',
        },
        {
          question: '기존 싱크대 철거비와 폐기물 처리비도 별도로 드나요?',
          answer: '대부분의 싱크대 전문 시공팀은 신규 설치 계약 시 기존 싱크대 무료 철거 및 폐기물 전량 수거를 기본 패키지로 포함합니다.',
        },
        {
          question: '주방 타일 시공도 싱크대 설치할 때 함께 가능한가요?',
          answer: '싱크대를 철거한 직후 타일을 덧방 시공하고 하루 양생 후 새 싱크대를 앉히는 것이 가장 깔끔하며, 타일 공임비 약 25만~40만원이 추가됩니다.',
        },
        {
          question: '시공 당일 몇 시간 만에 끝나나요?',
          answer: '철거 1~2시간, 본체 하부장·상부장 조립 및 수평 맞춤 3시간, 대리석 상판 접합 샌딩 2시간으로 보통 오전 8시 시작해 오후 3~4시면 당일 완공됩니다.',
        },
      ],
    },
  },
  {
    id: 'service-18',
    number: '18',
    title: '욕실 줄눈 시공비용',
    slug: 'tile-grout-repair',
    categoryId: 'interior',
    categoryName: '인테리어·시공',
    ruleId: 'rule-tile-grout-repair',
    shortDesc: '화장실 바닥 백시멘트 파내기, 폴리우레아 반짝이 및 프리미엄 케라폭시 에폭시 줄눈',
    icon: '✨',
    questions: [
      {
        id: 'area_scope',
        label: '줄눈 시공 구역',
        type: 'select',
        defaultValue: 'bath_2',
        options: [
          { label: '욕실 1개소 바닥만 (원룸/단독욕실)', value: 'bath_1', priceDelta: 100000 },
          { label: '욕실 2개소 바닥 세트 (공용 + 안방욕실)', value: 'bath_2', priceDelta: 180000, hint: '가장 많이 하는 기본 세트' },
          { label: '욕실 2개소 + 현관 바닥', value: 'bath_2_entry', priceDelta: 230000 },
          { label: '욕실 2개소 + 현관 + 베란다/세탁실 전체 패키지', value: 'full_home', priceDelta: 380000 },
        ],
        required: true,
      },
      {
        id: 'material_type',
        label: '줄눈 소재 종류',
        type: 'select',
        defaultValue: 'polyurea',
        options: [
          { label: '친환경 폴리우레아 (글리터 은은한 반짝이/스노우화이트)', value: 'polyurea', priceDelta: 0 },
          { label: '케라폭시 에폭시 무광 줄눈 (무광 호텔 타일 감성, 반영구)', value: 'kerapoxy', priceDelta: 150000, hint: '수명 10년 이상 강력 추천' },
        ],
        required: true,
      },
      {
        id: 'wall_included',
        label: '벽 타일 줄눈 추가 여부',
        type: 'select',
        defaultValue: 'floor_only',
        options: [
          { label: '바닥만 시공', value: 'floor_only', priceDelta: 0 },
          { label: '욕조/샤워부스 물 닿는 벽면 3면 추가', value: 'wall_shower', priceDelta: 180000 },
          { label: '욕실 전체 벽면 사방 시공', value: 'wall_all', priceDelta: 350000 },
        ],
        required: false,
      },
    ],
    evidence: {
      provider: '숨고(Soomgo) 줄눈 시공 견적 통계',
      sourceUrl: 'https://soomgo.com/prices/%EC%A4%84%EB%88%88-%EC%8B%9C%EA%B3%B5',
      basePrice: 400000,
      minPrice: 150000,
      maxPrice: 1000000,
      priceUnit: '건당 (평균 40만원 / 최저 15만 ~ 최고 100만원)',
      vatIncluded: true,
      travelFeeIncluded: true,
      materialsIncluded: true,
      surveyedAt: '2026-10-09',
      lastVerifiedAt: '2026-10-09',
      verificationStatus: 'verified',
      sourceType: 'platform_average',
      reliabilityLevel: 'high',
      notes: '숨고 플랫폼 실거래 데이터 기준. 줄눈 시공 평균 40만원 (최저 15만원, 최고 100만원). 시공 구역 수(욕실, 현관, 베란다) 및 소재(폴리우레아, 케라폭시)에 따라 상이.',
    },
    seo: {
      title: '화장실 욕실 줄눈 시공비용 견적 계산기 (케라폭시/폴리우레아) | 바로견적',
      description: '욕실 바닥 줄눈 시공비용, 케라폭시 무광 에폭시 줄눈 단가, 곰팡이 방지 실리콘 교체 견적을 비교해보세요.',
      keywords: ['욕실 줄눈 시공비용', '케라폭시 줄눈 가격', '화장실 줄눈 견적', '줄눈 시공 업체 비용', '욕실 곰팡이 줄눈'],
      h1: '욕실 줄눈 시공비용 계산기',
      canonicalPath: 'https://quote.info-myview.co.kr/estimate/tile-grout-repair/',
      faq: [
        {
          question: '줄눈 시공을 하면 곰팡이가 정말 안 생기나요?',
          answer: '네. 백시멘트는 미세 기공이 있어 물을 흡수해 곰팡이가 피지만, 폴리우레아나 케라폭시는 플라스틱/에폭시처럼 완벽한 방수 피막을 형성하여 오염물이 스며들지 않고 물걸레로 닦아집니다.',
        },
        {
          question: '케라폭시와 일반 줄눈의 차이는 무엇인가요?',
          answer: '일반 폴리우레아 줄눈은 액상 주입형으로 유광 반짝이 느낌이 나는 반면, 이탈리아 마페이사의 케라폭시는 무광 매트한 질감으로 호텔 타일처럼 고급스러우며 락스 청소에도 변색되지 않는 반영구적 내구성을 자랑합니다.',
        },
        {
          question: '시공 후 화장실은 언제부터 사용할 수 있나요?',
          answer: '폴리우레아 줄눈은 4~6시간 후 물 사용이 가능하며, 케라폭시 에폭시 줄눈은 완전 경화를 위해 약 24시간 동안 물 닿음을 금지해야 합니다.',
        },
        {
          question: '오래된 구축 아파트도 줄눈 시공이 가능한가요?',
          answer: '가능합니다. 다만 백시멘트가 돌처럼 단단하게 굳어있어 핸드 그라인더로 파내는 작업 난이도가 높아 신축 아파트 대비 2만~3만원의 구축 공임이 추가될 수 있습니다.',
        },
      ],
    },
  },
  {
    id: 'service-19',
    number: '19',
    title: '철거·원상복구 비용',
    slug: 'interior-demolition-restoration',
    categoryId: 'interior',
    categoryName: '인테리어·시공',
    ruleId: 'rule-interior-demolition-restoration',
    shortDesc: '상가 퇴거 원상복구, 주택 내부 가벽·싱크대·마루 바닥 철거 평당 폐기물 견적',
    icon: '🔨',
    questions: [
      {
        id: 'demolition_target',
        label: '철거 대상 및 장소',
        type: 'select',
        defaultValue: 'commercial_full',
        options: [
          { label: '상가/사무실 폐업 임대차 원상복구 (천장/바닥/가벽/간판 전량)', value: 'commercial_full', priceDelta: 1500000 },
          { label: '가정집 바닥재 철거 (온돌마루/강마루 기계 샌딩 철거)', value: 'floor_removal', priceDelta: 700000 },
          { label: '가정집 가벽 철거 + 문틀 제거 1~2개소', value: 'wall_partition', priceDelta: 450000 },
          { label: '욕실 1개소 전체 타일/위생도기 올철거', value: 'bath_demolition', priceDelta: 550000 },
        ],
        required: true,
      },
      {
        id: 'area_pyeong',
        label: '철거 면적 (평)',
        type: 'number',
        defaultValue: 15,
        min: 1,
        max: 100,
        step: 5,
        unit: '평',
        helpText: '철거 작업이 진행될 실평수를 입력하세요.',
        required: true,
      },
      {
        id: 'waste_handling',
        label: '폐기물 반출 환경',
        type: 'select',
        defaultValue: 'ev_cart',
        options: [
          { label: '화물 승강기 이용 가능 (대차 밀차 작업)', value: 'ev_cart', priceDelta: 0 },
          { label: '사다리차 이용 양하 (고층 창문 반출)', value: 'ladder', priceDelta: 150000 },
          { label: '엘리베이터 없는 계단 인력 곰방 (등짐 반출)', value: 'stairs_carry', priceDelta: 250000, hint: '인부 노임 추가' },
        ],
        required: true,
      },
    ],
    evidence: {
      provider: '숨고(Soomgo) 철거 견적 통계',
      sourceUrl: 'https://soomgo.com/prices/%EC%B2%A0%EA%B1%B0',
      basePrice: 600000,
      minPrice: 150000,
      maxPrice: 2700000,
      priceUnit: '건당 (평균 60만원 / 최저 15만 ~ 최고 270만원)',
      vatIncluded: true,
      travelFeeIncluded: true,
      materialsIncluded: true,
      surveyedAt: '2026-10-09',
      lastVerifiedAt: '2026-10-09',
      verificationStatus: 'verified',
      sourceType: 'platform_average',
      reliabilityLevel: 'high',
      notes: '숨고 플랫폼 실거래 데이터 기준. 철거 평균 60만원 (최저 15만원, 최고 270만원). 철거 대상(상가 원상복구, 마루/가벽 철거), 실평수, 폐기물 반출 방식에 따라 차이.',
    },
    seo: {
      title: '철거비용 원상복구 견적 계산기 (상가폐업/가벽/마루철거) | 바로견적',
      description: '상가 사무실 퇴거 원상복구 평당 비용, 아파트 강마루 기계 철거, 욕실 가벽 철거 및 폐기물 처리비용을 확인하세요.',
      keywords: ['철거비용', '상가 원상복구 비용', '폐업 철거 지원금', '마루 철거 비용', '아파트 내부 철거 견적'],
      h1: '철거·원상복구 비용 계산기',
      canonicalPath: 'https://quote.info-myview.co.kr/estimate/interior-demolition-restoration/',
      faq: [
        {
          question: '소상공인 폐업 시 철거비 지원금을 받을 수 있나요?',
          answer: '네. 소상공인시장진흥공단의 "희망리턴패키지 원상복구 지원사업"을 통해 평당 최대 13만원, 최대 250만원 한도로 실비 국비 지원을 신청하실 수 있습니다.',
        },
        {
          question: '마루 바닥 철거 시 샌딩(면갈이) 작업이 꼭 필요한가요?',
          answer: '네. 본드로 붙인 강마루/온돌마루를 기계로 뜯어내면 바닥에 접착제와 시멘트 찌꺼기가 남으므로, 새 바닥재(타일/장판)를 깔기 위해 다이아몬드 날 샌딩기로 평탄화 면갈이를 해야 합니다.',
        },
        {
          question: '철거 공사 시 아파트 관리실 동의서와 예치금이 필요한가요?',
          answer: '아파트나 상가 건물은 소음과 승강기 보양 문제로 입주민 동의서(과반수) 서명과 승강기 보양, 공사 예치금(통상 50만~100만원) 납부가 사전 필수입니다.',
        },
        {
          question: '폐기물은 건설폐기물 전용 마대에 버려야 하나요?',
          answer: '네. 콘크리트 잔재, 석고보드, 타일은 불연성 특수폐기물이므로 일반 종량제에 버릴 수 없고 정식 폐기물 집하장으로 반출 처리됩니다.',
        },
      ],
    },
  },
  {
    id: 'service-20',
    number: '20',
    title: '방충망 교체비용',
    slug: 'insect-screen-replacement',
    categoryId: 'interior',
    categoryName: '인테리어·시공',
    ruleId: 'rule-insect-screen-replacement',
    shortDesc: '미세먼지 차단 미세방충망, 부식 없는 모노필라멘트 30메쉬 창문 개수별 교체',
    icon: '🪟',
    questions: [
      {
        id: 'screen_material',
        label: '방충망 소재 종류',
        type: 'select',
        defaultValue: 'monofilament',
        options: [
          { label: '일반 알루미늄망 (가성비, 부식 쉬움)', value: 'aluminum', priceDelta: 30000 },
          { label: '블랙 코팅 모노필라멘트 미세방충망 (30메쉬 초파리 차단, 추천)', value: 'monofilament', priceDelta: 45000, hint: '녹슬지 않는 고강도 낚싯줄 소재' },
          { label: '스테인리스 0.4T 추락방지 안전방충망 (아이/반려동물 추락방지)', value: 'stainless_safety', priceDelta: 120000, hint: '하중 500kg 지지 잠금장치 결합' },
        ],
        required: true,
      },
      {
        id: 'large_window_count',
        label: '거실/안방 대창 개수 (높이 1.8m 이상)',
        type: 'number',
        defaultValue: 2,
        min: 0,
        max: 10,
        step: 1,
        unit: '개',
        helpText: '바닥부터 천장까지 이르는 큰 베란다 창틀 개수를 입력하세요.',
        required: true,
      },
      {
        id: 'small_window_count',
        label: '작은방/주방 중·소창 개수 (높이 1.2m 이하)',
        type: 'number',
        defaultValue: 3,
        min: 0,
        max: 10,
        step: 1,
        unit: '개',
        helpText: '주방, 세탁실, 작은방 반창 개수를 입력하세요.',
        required: true,
      },
      {
        id: 'dust_strip_replace',
        label: '물구멍 방충망 및 모헤어(털) 전면 교체',
        type: 'select',
        defaultValue: 'mohair_included',
        options: [
          { label: '방충망만 단순 교체', value: 'screen_only', priceDelta: 0 },
          { label: '방충망 + 창틀 틈새 모헤어 전면 교체 + 물구멍 스티커 서비스', value: 'mohair_included', priceDelta: 30000, hint: '날벌레 틈새 완벽 차단' },
        ],
        required: true,
      },
    ],
    evidence: {
      provider: '숨고(Soomgo) 방충망 설치 및 수리 견적 통계',
      sourceUrl: 'https://soomgo.com/prices/%EB%B0%A9%EC%B6%A9%EB%A7%9D-%EC%84%A4%EC%B9%98-%EC%88%98%EB%A6%AC',
      basePrice: 150000,
      minPrice: 40000,
      maxPrice: 400000,
      priceUnit: '건당 (평균 15만원 / 최저 4만 ~ 최고 40만원)',
      vatIncluded: true,
      travelFeeIncluded: true,
      materialsIncluded: true,
      surveyedAt: '2026-10-09',
      lastVerifiedAt: '2026-10-09',
      verificationStatus: 'verified',
      sourceType: 'platform_average',
      reliabilityLevel: 'high',
      notes: '숨고 플랫폼 실거래 데이터 기준. 방충망 설치 및 수리 평균 15만원 (최저 4만원, 최고 40만원). 창문 개수(대창/소창) 및 방충망 소재(알루미늄/미세방충망/안전망)에 따라 산정.',
    },
    seo: {
      title: '미세방충망 교체비용 창문 개수별 견적 계산기 (모노필라멘트/안전망) | 바로견적',
      description: '아파트 베란다 창문 미세방충망 교체 개당 단가, 모노필라멘트 30메쉬, 추락방지 안전망 패키지 비용을 계산하세요.',
      keywords: ['방충망 교체비용', '미세방충망 가격', '아파트 방충망 교체', '모노필라멘트 방충망', '추락방지 방충망 비용'],
      h1: '방충망 교체비용 계산기',
      canonicalPath: 'https://quote.info-myview.co.kr/estimate/insect-screen-replacement/',
      faq: [
        {
          question: '알루미늄망과 모노필라멘트 미세방충망의 수명 차이는 얼마나 되나요?',
          answer: '알루미늄망은 2~3년이 지나면 산성비와 매연에 부식되어 쇳가루가 날리고 쉽게 찢어집니다. 반면 특수 섬유인 모노필라멘트는 녹슬지 않아 10년 이상 반영구적으로 사용 가능합니다.',
        },
        {
          question: '미세방충망을 하면 바람이 안 통하지 않나요?',
          answer: '과거 촘촘망과 달리 최신 30메쉬 모노필라멘트는 극세사 가닥 구조로 제작되어 통풍율이 85% 이상 유지되면서도 날파리와 하루살이 진입을 100% 차단합니다.',
        },
        {
          question: '작업은 집 안에서 하나요, 밖에서 하나요?',
          answer: '먼지 발생을 방지하기 위해 집안에서는 창틀만 안전하게 탈거하고, 1층 주차장이나 야외 작업 공간에서 재단 및 압착 후 다시 댁내로 올려 장착합니다.',
        },
        {
          question: '물구멍 방충망은 왜 꼭 붙여야 하나요?',
          answer: '샷시 레일 하단의 빗물 빠짐 배수구멍(길이 3~5cm)은 바깥 날벌레가 집으로 기어들어오는 최대 통로이므로 미세 거름망 스티커를 부착해야 합니다.',
        },
      ],
    },
  },
  {
    id: 'service-21',
    number: '21',
    title: '블라인드·커튼 설치비용',
    slug: 'blinds-curtains-installation',
    categoryId: 'interior',
    categoryName: '인테리어·시공',
    ruleId: 'rule-blinds-curtains-installation',
    shortDesc: '암막커튼, 쉬폰 차르르 커튼 레일 시공, 콤비·우드 블라인드 맞춤 실측 시공비',
    icon: '🪟',
    questions: [
      {
        id: 'product_type',
        label: '제품 및 시공 종류',
        type: 'select',
        defaultValue: 'chiffon_curtain',
        options: [
          { label: '콤비 롤 블라인드 (채광 조절 가성비)', value: 'combi_blind', priceDelta: 120000 },
          { label: '차르르 쉬폰 + 암막 2중 커튼 레일 세트 (호텔식 거실)', value: 'chiffon_curtain', priceDelta: 280000, hint: '거실 창 기준 맞춤 자재' },
          { label: '천연 오동나무 우드 블라인드 (고급 서재/안방)', value: 'wood_blind', priceDelta: 220000 },
          { label: '고객 직접 구매 제품 단순 시공 (창당 출장공임만)', value: 'labor_only', priceDelta: 60000, hint: '레일/브래킷 피스 고정' },
        ],
        required: true,
      },
      {
        id: 'window_count',
        label: '설치 창문 개소 수',
        type: 'select',
        defaultValue: '2',
        options: [
          { label: '1개 창 (거실 또는 방 1개)', value: '1', priceDelta: 0 },
          { label: '2개 창 (거실 + 안방)', value: '2', priceDelta: 140000 },
          { label: '3개 창 (거실 + 안방 + 작은방)', value: '3', priceDelta: 260000 },
          { label: '집 전체 창문 4~5개소 일체', value: 'all_home', priceDelta: 450000 },
        ],
        required: true,
      },
      {
        id: 'ceiling_material',
        label: '천장 커튼박스 재질 환경',
        type: 'select',
        defaultValue: 'wood_box',
        options: [
          { label: '목재 합판 커튼박스 (일반 직결 피스 체결)', value: 'wood_box', priceDelta: 0 },
          { label: '석고보드 1P/2P (토글앙카/나비앙카 특수 보강 필요)', value: 'drywall_anchor', priceDelta: 20000, hint: '추락 방지 앙카 작업' },
          { label: '콘크리트 직부 천장 (해머드릴 칼브럭 타공)', value: 'concrete_drill', priceDelta: 30000 },
        ],
        required: true,
      },
    ],
    evidence: {
      provider: '숨고(Soomgo) 블라인드/커튼 설치 및 수리 견적 통계',
      sourceUrl: 'https://soomgo.com/prices/%EB%B8%94%EB%9D%BC%EC%9D%B8%EB%93%9C-%EC%BB%A4%ED%8A%BC-%EC%84%A4%EC%B9%98-%EC%88%98%EB%A6%AC',
      basePrice: 320000,
      minPrice: 50000,
      maxPrice: 850000,
      priceUnit: '건당 (평균 32만원 / 최저 5만 ~ 최고 85만원)',
      vatIncluded: true,
      travelFeeIncluded: true,
      materialsIncluded: true,
      surveyedAt: '2026-10-09',
      lastVerifiedAt: '2026-10-09',
      verificationStatus: 'verified',
      sourceType: 'platform_average',
      reliabilityLevel: 'high',
      notes: '숨고 플랫폼 실거래 데이터 기준. 블라인드/커튼 설치 및 수리 평균 32만원 (최저 5만원, 최고 85만원). 단순 설치 대행(5만~10만원)과 자재 맞춤 제작 일체(25만~85만원)에 따라 구분.',
    },
    seo: {
      title: '커튼 블라인드 설치비용 견적 계산기 (쉬폰/암막/우드블라인드) | 바로견적',
      description: '거실 차르르 쉬폰 커튼, 암막커튼 맞춤 제작 가격, 콤비 블라인드 및 단순 레일 설치 출장 공임을 계산하세요.',
      keywords: ['커튼 설치비용', '블라인드 시공비', '쉬폰커튼 가격', '우드블라인드 견적', '커튼 레일 설치 공임'],
      h1: '블라인드·커튼 설치비용 계산기',
      canonicalPath: 'https://quote.info-myview.co.kr/estimate/blinds-curtains-installation/',
      faq: [
        {
          question: '커튼 맞춤 시 "나비주름 2배"란 무엇인가요?',
          answer: '원단을 창문 가로 폭의 2배로 넉넉하게 사용하여 상단에 풍성한 S자 주름을 영구 봉제한 호텔식 가공법으로, 민자 커튼에 비해 훨씬 단정하고 우아한 분위기를 연출합니다.',
        },
        {
          question: '석고보드 천장인데 커튼이 떨어지지 않을까요?',
          answer: '일반 나사못을 박으면 석고가 부서져 떨어집니다. 전문 기사는 10kg 이상을 지탱하는 나비앙카(토글앙카)를 사용하거나 천장 내부 목상 뼈대를 찾아 피스를 고정하므로 안전합니다.',
        },
        {
          question: '직접 구매한 이케아 커튼봉도 설치 대행해 주나요?',
          answer: '네. 구매해 두신 블라인드나 커튼봉, 레일이 있다면 개소당 2만 5천원~4만원 수준의 단순 설치 출장 공임으로 의뢰하실 수 있습니다.',
        },
        {
          question: '방문 실측 서비스는 무료인가요?',
          answer: '맞춤 제작 업체를 통해 원단과 블라인드를 함께 주문하시면 전문 실측 기사의 방문 실측과 샘플 북 안내가 무료로 제공되는 곳이 많습니다.',
        },
      ],
    },
  },
  {
    id: 'service-25',
    number: '25',
    title: '옥상·건물 방수공사 비용',
    slug: 'rooftop-waterproofing',
    categoryId: 'interior',
    categoryName: '인테리어·시공',
    ruleId: 'rule-rooftop-waterproofing',
    shortDesc: '빌라·상가주택 옥상 우레탄 3회 도포 및 복합시트 영구 방수공사 평당 견적',
    icon: '🏢',
    questions: [
      {
        id: 'rooftop_area',
        label: '옥상 바닥 면적 (평)',
        type: 'number',
        defaultValue: 30,
        min: 10,
        max: 200,
        step: 5,
        unit: '평',
        helpText: '방수 시공이 필요한 옥상 바닥 실평수를 입력하세요.',
        required: true,
      },
      {
        id: 'waterproof_method',
        label: '방수 공법 종류',
        type: 'select',
        defaultValue: 'urethane_3_coat',
        options: [
          { label: '우레탄 도막 방수 3회 도포 (하도 프라이머 + 중도 3mm + 상도 코팅)', value: 'urethane_3_coat', priceDelta: 3000000, hint: '가장 널리 쓰이는 표준 방수' },
          { label: '복합 시트 방수 (단열 방수 시트 + 우레탄 함침, 수명 15년 이상)', value: 'sheet_composite', priceDelta: 4500000, hint: '크랙 균열에 절대 찢어지지 않는 최상급' },
        ],
        required: true,
      },
      {
        id: 'surface_grinding',
        label: '바닥 기존 우레탄 들뜸 상태 (면갈이 필요 여부)',
        type: 'select',
        defaultValue: 'partial_grinding',
        options: [
          { label: '경미 (기존 방수층 양호, 청소 및 부분 보수)', value: 'light_clean', priceDelta: 0 },
          { label: '중간 (군데군데 들뜸, 고압세척 + 부분 그라인딩)', value: 'partial_grinding', priceDelta: 500000 },
          { label: '심각 (기존 우레탄 전체 박리 부풀림, 바닥 전면 연삭)', value: 'full_grinding', priceDelta: 1200000, hint: '쌍발기 연삭기 면갈이 필수' },
        ],
        required: true,
      },
    ],
    evidence: {
      provider: '숨고(Soomgo) 옥상공사/방수 견적 통계',
      sourceUrl: 'https://soomgo.com/prices/%EC%98%A5%EC%83%81%EA%B3%B5%EC%82%AC-%EB%B0%A9%EC%88%98',
      basePrice: 3500000,
      minPrice: 1750000,
      maxPrice: 5600000,
      priceUnit: '시공당 (평균 350만원 / 최저 175만 ~ 최고 560만원)',
      vatIncluded: true,
      travelFeeIncluded: true,
      materialsIncluded: true,
      surveyedAt: '2026-10-09',
      lastVerifiedAt: '2026-10-09',
      verificationStatus: 'verified',
      sourceType: 'platform_average',
      reliabilityLevel: 'high',
      notes: '숨고 플랫폼 실거래 데이터 기준. 원문 페이지 평균 시세 3,504,433원(UI 표시용 만원 단위 반올림 3,500,000원, 최저 1,750,000원, 최고 5,600,000원). 우레탄 도막 3회 도포 및 복합 시트 방수 공법, 바닥 연삭 면갈이 여부에 따라 변동.',
    },
    seo: {
      title: '옥상 방수공사 비용 평당 단가 계산기 (우레탄/복합시트방수) | 바로견적',
      description: '빌라 옥상 방수비용 평당 단가, 녹색 우레탄 3회 도포, 바닥 면갈이, 복합시트 영구방수 실시간 공사 견적을 산출해보세요.',
      keywords: ['옥상 방수공사 비용', '우레탄 방수 평당 가격', '빌라 옥상 방수 견적', '옥상 누수 공사비', '복합시트 방수 비용'],
      h1: '옥상·건물 방수공사 비용 계산기',
      canonicalPath: 'https://quote.info-myview.co.kr/estimate/rooftop-waterproofing/',
      faq: [
        {
          question: '우레탄 방수 시 가장 중요한 단계는 무엇인가요?',
          answer: '기존 들뜬 우레탄을 연삭기(면갈이)로 바닥 콘크리트까지 완벽히 갈아내고 바닥 습기를 8% 이하로 바짝 말리는 "바탕정리"입니다. 습기가 남아있으면 한여름에 기포가 생겨 우레탄이 부풀어 터집니다.',
        },
        {
          question: '우레탄 방수의 권장 도막 두께는 몇 mm인가요?',
          answer: 'KS 규격 기준 우레탄 중도는 최소 3mm 두께 이상을 도포해야 5~7년 이상 방수 성능이 유지됩니다. 얇게 1~2mm만 펴 바르는 저가 덤핑 시공은 2년 내에 찢어집니다.',
        },
        {
          question: '방수 공사 후 보증 기간은 얼마나 되나요?',
          answer: '전문 도장방수 면허 업체는 우레탄 3회 시공 시 통상 3년, 복합 시트 방수 시 최대 5년~7년 무상 하자보증서를 발급합니다.',
        },
        {
          question: '공사 기간 동안 옥상 출입이 통제되나요?',
          answer: '청소 및 면갈이 1일, 하도/중도 도포 및 경화 2~3일, 상도 코팅 1일로 약 4~5일 소요되며 경화 중 밟으면 찢어지므로 출입이 제한됩니다.',
        },
      ],
    },
  },
];
