import type { ServiceDefinition } from '../types';

export const MOVING_SERVICES: ServiceDefinition[] = [
  {
    id: 'service-03',
    number: '03',
    title: '원룸·소형이사 예상비용',
    slug: 'studio-moving',
    categoryId: 'moving',
    categoryName: '이사·운송·폐기물',
    ruleId: 'rule-studio-moving',
    shortDesc: '1인 가구, 오피스텔 용달이사 및 반포장이사 거리·인력별 예상 견적',
    icon: '📦',
    questions: [
      {
        id: 'moving_type',
        label: '이사 방식',
        type: 'select',
        defaultValue: 'semi_package',
        options: [
          { label: '차량만 대여 (운송만, 본인이 상하차)', value: 'transport_only', priceDelta: 50000, hint: '가장 저렴한 단순 차량 운행' },
          { label: '일반 이사 (기사님과 함께 짐 운반, 본인이 포장)', value: 'general', priceDelta: 120000 },
          { label: '반포장 이사 (기사님이 포장자재 지참 및 큰짐 포장)', value: 'semi_package', priceDelta: 180000, hint: '1인 가구 최다 선호' },
          { label: '원룸 포장 이사 (포장부터 정리까지 전담)', value: 'full_package', priceDelta: 280000 },
        ],
        required: true,
      },
      {
        id: 'distance_km',
        label: '이동 거리 (km)',
        type: 'number',
        defaultValue: 10,
        min: 1,
        max: 100,
        step: 5,
        unit: 'km',
        helpText: '출발지에서 도착지까지의 대략적인 차량 이동 거리를 입력하세요.',
        required: true,
      },
      {
        id: 'elevator_status',
        label: '엘리베이터 환경',
        type: 'select',
        defaultValue: 'both_ev',
        options: [
          { label: '출발지/도착지 모두 승강기 있음', value: 'both_ev', priceDelta: 0 },
          { label: '한쪽 계단 작업 (2~3층)', value: 'one_stairs', priceDelta: 30000 },
          { label: '양쪽 모두 계단 작업', value: 'both_stairs', priceDelta: 70000 },
        ],
        required: true,
      },
      {
        id: 'helper_needed',
        label: '인부 추가 여부',
        type: 'select',
        defaultValue: 'driver_only',
        options: [
          { label: '기사님 1인 (고객 본인 함께 운반)', value: 'driver_only', priceDelta: 0 },
          { label: '전문 인부 1명 추가 (총 2인 작업)', value: 'extra_worker', priceDelta: 100000, hint: '무거운 양문형 냉장고/침대 분해 시 필수' },
        ],
        required: true,
      },
    ],
    evidence: {
      provider: '전국화물자동차운송사업연합회 및 용달이사 마켓 실거래가',
      sourceUrl: 'https://soomgo.com/costs/studio-moving',
      basePrice: 120000,
      priceUnit: '원룸 반포장 10km 기준 15만~22만원 선',
      vatIncluded: true,
      travelFeeIncluded: true,
      materialsIncluded: true,
      surveyedAt: '2026-08-20',
      lastVerifiedAt: '2026-10-01',
      reliabilityLevel: 'high',
      notes: '말일/월말 및 손없는날(음력 9, 10일) 이사 시 20~30% 할증 발생 가능.',
    },
    seo: {
      title: '원룸이사 비용 견적 계산기 (용달/일반/반포장) | 바로견적',
      description: '원룸·소형 오피스텔 이사 차량대여, 일반이사, 반포장이사 거리별·층수별 예상비용을 바로 계산해보세요.',
      keywords: ['원룸이사 비용', '용달이사 견적', '원룸 반포장이사 비용', '소형이사 가격', '원룸이사 사다리차'],
      h1: '원룸·소형이사 예상비용 계산기',
      canonicalPath: 'https://quote.info-myview.co.kr/estimate/studio-moving/',
      faq: [
        {
          question: '일반이사와 반포장이사의 가장 큰 차이는 무엇인가요?',
          answer: '일반이사는 고객이 이사 전 직접 박스에 모든 짐을 싸두어야 하며 기사님은 운반만 돕습니다. 반포장이사는 기사님이 바구니와 박스를 가져와 주방 잔짐을 제외한 큰 짐들을 직접 포장하고 운반해 줍니다.',
        },
        {
          question: '계단 작업 시 추가 요금이 왜 발생하나요?',
          answer: '승강기가 없는 2층 이상 건물은 계단으로 가구와 가전을 직접 짊어지고 내려와야 하므로 체력 소모와 작업 시간이 2배 이상 소요되어 계단 수고비(3~5만원)가 발생합니다.',
        },
        {
          question: '월말이나 주말에 이사하면 비용이 더 비싼가요?',
          answer: '네. 통상 금요일/토요일, 월말, 그리고 전통적인 손 없는 날은 예약이 몰려 기본 견적에서 3만~7만원의 성수기 할증이 붙습니다.',
        },
        {
          question: '침대 프레임 분해와 조립도 기사님이 해주시나요?',
          answer: '반포장 또는 포장이사를 선택하시면 기본적인 육각렌치 침대 프레임 분해 및 재조립은 기사님이 처리해 드립니다.',
        },
      ],
    },
  },
  {
    id: 'service-04',
    number: '04',
    title: '포장이사 예상비용',
    slug: 'full-service-moving',
    categoryId: 'moving',
    categoryName: '이사·운송·폐기물',
    ruleId: 'rule-full-service-moving',
    shortDesc: '아파트·주택 가구 전체 포장·운반·배치·주방정리 포함 포장이사 견적',
    icon: '🚛',
    questions: [
      {
        id: 'truck_tonnage',
        label: '예상 짐량 (톤수 / 평형)',
        type: 'select',
        defaultValue: '5_ton',
        options: [
          { label: '2.5톤 (투룸 / 15~20평형 / 부부 2인가구)', value: '2.5_ton', priceDelta: 850000 },
          { label: '5톤 (국민평형 24~34평형 / 3~4인 가구)', value: '5_ton', priceDelta: 1200000, hint: '가장 많은 표준 가구형' },
          { label: '6톤 (34평형 짐 많은 집 / 방 3개 이상)', value: '6_ton', priceDelta: 1450000 },
          { label: '7.5톤 이상 (40평형대 대형 평수)', value: '7.5_ton', priceDelta: 1800000 },
        ],
        required: true,
      },
      {
        id: 'moving_distance',
        label: '이동 거리 (km)',
        type: 'number',
        defaultValue: 15,
        min: 1,
        max: 200,
        step: 10,
        unit: 'km',
        helpText: '시내 이동(30km 이하)은 기본요금이며 장거리 시 고속도로 통행료 및 유류비가 가산됩니다.',
        required: true,
      },
      {
        id: 'ladder_usage',
        label: '사다리차 이용 계획',
        type: 'select',
        defaultValue: 'both_sides',
        options: [
          { label: '양쪽 모두 사다리차 사용 (출발지 + 도착지)', value: 'both_sides', priceDelta: 280000, hint: '사다리차 2회 비용' },
          { label: '한쪽만 사다리차 사용 (한쪽은 엘리베이터 이용)', value: 'one_side', priceDelta: 140000 },
          { label: '사다리차 미사용 (양쪽 모두 엘리베이터 이용)', value: 'none', priceDelta: 0, hint: '아파트 엘리베이터 이용료(10~20만) 별도 관리사무소 납부' },
        ],
        required: true,
      },
      {
        id: 'peak_day',
        label: '이사 일정 구분',
        type: 'select',
        defaultValue: 'weekday',
        options: [
          { label: '평일 (월~목)', value: 'weekday', priceDelta: 0 },
          { label: '금요일 / 주말 (토~일)', value: 'weekend', priceDelta: 150000 },
          { label: '손 없는 날 (극성수기)', value: 'lucky_day', priceDelta: 300000, hint: '예약 조기 마감 주의' },
        ],
        required: true,
      },
    ],
    evidence: {
      provider: '전국화물자동차운송주선사업연합회 및 공정위 표준약관 포장이사 시세',
      sourceUrl: 'https://soomgo.com/costs/full-service-moving',
      basePrice: 1100000,
      priceUnit: '5톤 트럭 기준 110만~150만원 선 (사다리차 별도)',
      vatIncluded: true,
      travelFeeIncluded: true,
      materialsIncluded: true,
      surveyedAt: '2026-08-22',
      lastVerifiedAt: '2026-10-01',
      reliabilityLevel: 'high',
      notes: '사다리차 사용료 및 아파트 엘리베이터 사용료는 관리사무소 기준 별도 지출.',
    },
    seo: {
      title: '포장이사 비용 견적 계산기 (2.5톤/5톤/사다리차/손없는날) | 바로견적',
      description: '아파트, 주택 포장이사 평형별 톤수, 이동거리, 사다리차 비용, 손없는날 할증을 반영한 실시간 예상견적을 산출해보세요.',
      keywords: ['포장이사 비용', '5톤 포장이사 견적', '아파트 포장이사 비용', '포장이사 사다리차 비용', '손없는날 이사비용'],
      h1: '포장이사 예상비용 계산기',
      canonicalPath: 'https://quote.info-myview.co.kr/estimate/full-service-moving/',
      faq: [
        {
          question: '포장이사 시 작업 인원은 몇 명이 투입되나요?',
          answer: '5톤 트럭 기준 통상 남성 전문 패커 3명과 주방 정리 전문 헬퍼(여성) 1명 등 총 4인 1조로 구성되는 것이 업계 표준입니다.',
        },
        {
          question: '에어컨 탈거 및 벽걸이 TV 해체도 포장이사에 포함되나요?',
          answer: '단순 배관 절단 및 기기 철거는 무료로 해주지만, 새집에서의 배관 연장 및 벽 타공 설치는 별도 전문 설치 기사 비용이 발생합니다.',
        },
        {
          question: '포장이사 중 가구 파손이 발생하면 어떻게 보상받나요?',
          answer: '정식 화물자동차운송주선사업 허가증과 적재물 배상책임보험에 가입된 관허 업체를 이용하셔야 사고 발생 시 즉각적인 현금 배상 또는 수리가 보장됩니다.',
        },
        {
          question: '방문 견적을 꼭 받아야 하는 이유는 무엇인가요?',
          answer: '유선 전화상 견적은 가구 수납장 내부 짐과 발코니 짐을 과소평가하여 당일 트럭 추가(2.5톤 추가 40~50만) 분쟁이 생기기 쉬우므로, 3개 이상 업체 방문견적이 필수입니다.',
        },
      ],
    },
  },
  {
    id: 'service-08',
    number: '08',
    title: '폐가구·폐기물 수거비용',
    slug: 'bulky-waste-removal',
    categoryId: 'moving',
    categoryName: '이사·운송·폐기물',
    ruleId: 'rule-bulky-waste-removal',
    shortDesc: '장롱, 침대, 쇼파 등 대형 폐가구 및 가정·상가 폐기물 방문 수거 처리비',
    icon: '🗑️',
    questions: [
      {
        id: 'waste_type',
        label: '폐기물 종류 및 수량',
        type: 'select',
        defaultValue: 'sofa_bed',
        options: [
          { label: '단품 대형가구 1~2점 (장롱/쇼파/침대 중 1개)', value: 'single_item', priceDelta: 80000 },
          { label: '복합 가구 3~4점 (침대 + 장롱 + 식탁 세트)', value: 'sofa_bed', priceDelta: 180000 },
          { label: '1톤 트럭 반차분 (소형 이사 폐기물 전체)', value: 'half_truck', priceDelta: 280000 },
          { label: '1톤 트럭 1대 가득 (가정집 정리, 유품정리)', value: 'full_truck', priceDelta: 450000, hint: '잡쓰레기 + 목재 전량 수거' },
        ],
        required: true,
      },
      {
        id: 'disassembly_needed',
        label: '가구 분해 및 해체 작업',
        type: 'select',
        defaultValue: 'disassembly',
        options: [
          { label: '분해 불필요 (문 밖으로 바로 배출 가능)', value: 'none', priceDelta: 0 },
          { label: '붙박이장 / 벙커침대 / 대형슬라이딩장 분해 필요', value: 'disassembly', priceDelta: 40000, hint: '공구 해체 인건비 가산' },
        ],
        required: true,
      },
      {
        id: 'haul_environment',
        label: '반출 환경',
        type: 'select',
        defaultValue: 'ev_normal',
        options: [
          { label: '엘리베이터 이용 가능 (1층 또는 승강기)', value: 'ev_normal', priceDelta: 0 },
          { label: '승강기 없는 계단 2~3층 (인력 반출)', value: 'stairs', priceDelta: 50000 },
          { label: '사다리차 필요 (창문으로만 내릴 수 있는 대형가구)', value: 'ladder', priceDelta: 120000 },
        ],
        required: true,
      },
    ],
    evidence: {
      provider: '생활폐기물 수집운반 허가업체 및 한국환경공단 폐기물 수수료',
      sourceUrl: 'https://soomgo.com/costs/bulky-waste-removal',
      basePrice: 150000,
      priceUnit: '1톤 1차 기준 40만~55만원 선 (단품 5만~10만)',
      vatIncluded: true,
      travelFeeIncluded: true,
      materialsIncluded: true,
      surveyedAt: '2026-08-25',
      lastVerifiedAt: '2026-10-01',
      reliabilityLevel: 'high',
      notes: '지자체 대형폐기물 스티커 부착 후 1층 직접 배출 대비, 집안 방문 철거·수거 인건비 포함 기준.',
    },
    seo: {
      title: '폐가구·폐기물 수거비용 견적 계산기 (침대/장롱/1톤트럭) | 바로견적',
      description: '장롱, 매트리스, 소파 등 대형 폐가구 집안 직접 방문 수거 및 1톤 트럭 폐기물 처리비용 견적을 확인하세요.',
      keywords: ['폐가구 수거비용', '대형폐기물 방문수거', '침대 버리는 비용', '장롱 철거 버리기', '1톤 폐기물 처리비용'],
      h1: '폐가구·폐기물 수거비용 계산기',
      canonicalPath: 'https://quote.info-myview.co.kr/estimate/bulky-waste-removal/',
      faq: [
        {
          question: '주민센터 스티커를 사서 버리는 것과 방문 수거 업체의 차이는 무엇인가요?',
          answer: '주민센터 폐기물 스티커는 본인이 직접 아파트 분리수거장이나 도로변 1층까지 무거운 가구를 운반해 내놓아야 합니다. 반면 방문 수거 업체는 집 안에서 가구를 직접 분해하고 트럭에 실어 폐기장까지 운반해 드립니다.',
        },
        {
          question: '가전제품은 무상 수거가 가능한가요?',
          answer: '냉장고, 세탁기 등 대형 폐가전은 한국전자제품자원순환공제조합(1599-0903) 폐가전 무상방문수거 서비스를 이용하시면 무료 배출이 가능합니다.',
        },
        {
          question: '1톤 트럭 1차 가득 실으면 비용이 얼마나 드나요?',
          answer: '폐기물 매립장 반입 수수료와 인건비(2인), 유류비를 포함하여 1톤 트럭 1대 가득 기준 통상 40만~55만원 선입니다.',
        },
        {
          question: '가구 안에 있는 옷이나 잡동사니도 함께 버려주나요?',
          answer: '네. 포대자루(마대)를 준비해 옷가지, 식기, 생활 쓰레기를 한꺼번에 담아 트럭에 실어 폐기해 드리는 가정집 비우기 서비스가 가능합니다.',
        },
      ],
    },
  },
  {
    id: 'service-12',
    number: '12',
    title: '용달·화물 운송비용',
    slug: 'freight-truck-delivery',
    categoryId: 'moving',
    categoryName: '이사·운송·폐기물',
    ruleId: 'rule-freight-truck-delivery',
    shortDesc: '다마스, 라보, 1톤 트럭 단거리 및 전국 장거리 화물 운송 거리별 표준운임',
    icon: '🚚',
    questions: [
      {
        id: 'vehicle_type',
        label: '운송 차량 종류',
        type: 'select',
        defaultValue: 'truck_1ton',
        options: [
          { label: '다마스 (박스짐 10개 내외, 소형 물품)', value: 'damas', priceDelta: 35000 },
          { label: '라보 (탁자, 싱글 매트리스, 중형 물품)', value: 'labo', priceDelta: 45000 },
          { label: '1톤 카고 (오픈형 트럭, 표준 화물)', value: 'truck_1ton', priceDelta: 60000, hint: '가장 대중적인 화물차' },
          { label: '1톤 호루 / 탑차 (비·눈 날씨 안심 밀폐형)', value: 'top_1ton', priceDelta: 75000 },
        ],
        required: true,
      },
      {
        id: 'distance_km',
        label: '운송 거리 (km)',
        type: 'number',
        defaultValue: 20,
        min: 1,
        max: 400,
        step: 10,
        unit: 'km',
        helpText: '상차지에서 하차지까지의 내비게이션 주행 거리를 입력하세요.',
        required: true,
      },
      {
        id: 'labor_help',
        label: '상하차 인력 도움',
        type: 'select',
        defaultValue: 'driver_help',
        options: [
          { label: '차량만 이용 (상하차 고객 전담, 기사님 운전만)', value: 'drive_only', priceDelta: 0 },
          { label: '기사님 상하차 도움 (차량 바로 앞까지만 함께 운반)', value: 'driver_help', priceDelta: 20000 },
          { label: '집 내부까지 기사님 동행 운반 (엘리베이터 이용)', value: 'inside_ev', priceDelta: 40000 },
          { label: '계단 2층 이상 집 안까지 운반 (수고비)', value: 'stairs', priceDelta: 70000 },
        ],
        required: true,
      },
    ],
    evidence: {
      provider: '전국화물운송주선연합회 권장운임 및 전국화물24시 표준콜 시세',
      sourceUrl: 'https://soomgo.com/costs/freight-delivery',
      basePrice: 50000,
      priceUnit: '1톤 서울시내(15km) 기본 5만~7만원, 인력도움 2만~4만',
      vatIncluded: true,
      travelFeeIncluded: true,
      materialsIncluded: true,
      surveyedAt: '2026-08-28',
      lastVerifiedAt: '2026-10-01',
      reliabilityLevel: 'high',
      notes: '고속도로 통행료는 실비 청구. 기사 수작업 상하차 시간 30분 초과 시 대기료 1~2만원 발생.',
    },
    seo: {
      title: '용달 화물 운송비용 계산기 (1톤/다마스/거리별 운임) | 바로견적',
      description: '1톤 트럭, 다마스, 라보 거리별 전국 화물 운송비와 기사님 상하차 인력 추가비용을 실시간으로 계산해보세요.',
      keywords: ['용달 운송비용', '1톤 트럭 화물비', '다마스 퀵 요금', '거리별 용달비용', '1톤 용달 가격'],
      h1: '용달·화물 운송비용 계산기',
      canonicalPath: 'https://quote.info-myview.co.kr/estimate/freight-truck-delivery/',
      faq: [
        {
          question: '기본 용달 요금에는 짐을 옮겨주는 비용이 포함되어 있나요?',
          answer: '아닙니다. 기본 용달 운임은 차량 운전만 포함되는 조건입니다. 짐을 트럭에 싣고 내리는 작업에 기사님 도움을 받으시려면 상하차 수고비(2~4만원)가 추가됩니다.',
        },
        {
          question: '비나 눈이 오는 날에도 1톤 오픈 트럭을 이용할 수 있나요?',
          answer: '기사님이 방수 방수포(갑바)를 덮어주지만, 가구와 가전의 완벽한 보호를 위해서는 탑차나 호루(천막형) 차량을 배차 요청하시는 것이 안전합니다.',
        },
        {
          question: '동승(운전석 옆자리 탑승)이 가능한가요?',
          answer: '네. 짐과 함께 출발지에서 도착지까지 기사님 차량에 1명 동승하는 것은 대부분 무료로 협의 가능합니다.',
        },
        {
          question: '고속도로 톨게이트 비용은 누가 내나요?',
          answer: '거리 운임과 별도로 실제 발생한 고속도로 통행료는 하차 시 영수증 기준으로 고객이 정산하는 것이 관례입니다.',
        },
      ],
    },
  },
  {
    id: 'service-23',
    number: '23',
    title: '이사 사다리차 이용비용',
    slug: 'ladder-truck-moving',
    categoryId: 'moving',
    categoryName: '이사·운송·폐기물',
    ruleId: 'rule-ladder-truck-moving',
    shortDesc: '아파트, 빌라 고층 이사 및 가구·자재 양중 사다리차 층수·시간별 협회 표준요금',
    icon: '🪜',
    questions: [
      {
        id: 'floor_range',
        label: '작업 층수',
        type: 'select',
        defaultValue: 'floor_6_10',
        options: [
          { label: '2층 ~ 5층 (저층형)', value: 'floor_2_5', priceDelta: 120000 },
          { label: '6층 ~ 10층 (중층형)', value: 'floor_6_10', priceDelta: 140000, hint: '가장 일반적인 아파트 층수' },
          { label: '11층 ~ 15층 (고층형)', value: 'floor_11_15', priceDelta: 170000 },
          { label: '16층 ~ 20층 (초고층형)', value: 'floor_16_20', priceDelta: 210000 },
          { label: '21층 ~ 25층 (특수 고소차량)', value: 'floor_21_25', priceDelta: 270000 },
        ],
        required: true,
      },
      {
        id: 'work_type',
        label: '작업 분량 및 소요 시간',
        type: 'select',
        defaultValue: 'moving_one_trip',
        options: [
          { label: '단품 가구/가전 1점 단순 양중 (30분 이내)', value: 'single_lift', priceDelta: -30000 },
          { label: '이사 1회 올림/내림 (5톤 1차 기준 약 1~2시간)', value: 'moving_one_trip', priceDelta: 0 },
          { label: '반나절 대여 (3~4시간 연속 시공 자재 양중)', value: 'half_day', priceDelta: 150000 },
          { label: '종일 대여 (8시간 철거·인테리어 현장)', value: 'full_day', priceDelta: 350000 },
        ],
        required: true,
      },
      {
        id: 'ground_condition',
        label: '현장 진입 환경',
        type: 'select',
        defaultValue: 'normal',
        options: [
          { label: '사다리차 정면 주차 가능 (화단/장애물 없음)', value: 'normal', priceDelta: 0 },
          { label: '지하주차장 상부 슬라브 진입 또는 화단 넘김 작업', value: 'difficult', priceDelta: 30000, hint: '안전 아웃트리거 특수 보강 필요' },
        ],
        required: false,
      },
    ],
    evidence: {
      provider: '전국사다리차협회 공식 표준 요금표',
      sourceUrl: 'https://soomgo.com/costs/ladder-truck',
      basePrice: 130000,
      priceUnit: '5톤 1회 10층 이하 13만~15만원, 15층 17만~19만원',
      vatIncluded: true,
      travelFeeIncluded: true,
      materialsIncluded: true,
      surveyedAt: '2026-08-30',
      lastVerifiedAt: '2026-10-01',
      reliabilityLevel: 'high',
      notes: '협회 표준 가격제가 전국적으로 정착되어 있어 층수 및 톤수에 따른 단가가 가장 표준화된 서비스.',
    },
    seo: {
      title: '이사 사다리차 비용 층수별 요금표 계산기 (2층~25층) | 바로견적',
      description: '아파트 이사 사다리차 층수별(2층부터 25층까지) 공식 요금표와 단품 양중, 시간제 대여 예상비용을 확인하세요.',
      keywords: ['사다리차 비용', '사다리차 요금표', '이사 사다리차 가격', '사다리차 층수별 비용', '가구 사다리차 올림 비용'],
      h1: '이사 사다리차 이용비용 계산기',
      canonicalPath: 'https://quote.info-myview.co.kr/estimate/ladder-truck-moving/',
      faq: [
        {
          question: '사다리차 비용은 올릴 때와 내릴 때 각각 내야 하나요?',
          answer: '네. 출발지에서 짐을 내릴 때 1회, 도착지에서 짐을 올릴 때 1회 총 2회의 사다리차 비용이 각각 발생합니다.',
        },
        {
          question: '사다리차 진입이 불가능한 아파트는 어떻게 하나요?',
          answer: '지하주차장 전용 입구이거나 지상 도로가 없는 신축 공원형 아파트는 엘리베이터로 짐을 옮겨야 하며, 아파트 관리사무소에 승강기 사용료(통상 10만~25만원)를 지불해야 합니다.',
        },
        {
          question: '가구 1개만 올리는데도 1회 요금을 다 내야 하나요?',
          answer: '소파나 냉장고 1점만 올리는 30분 이내 단순 양중은 일반 이사 1회 요금보다 약 2만~3만원 할인된 단품 할인 요금이 적용됩니다.',
        },
        {
          question: '비나 강풍이 부는 날에도 사다리차를 탈 수 있나요?',
          answer: '순간 풍속이 강한 날은 사다리 프레임이 흔들려 전도 위험이 있으므로 안전 규정상 작업이 일시 중단될 수 있습니다.',
        },
      ],
    },
  },
];
