import type { ServiceDefinition } from '../types';

export const PLUMBING_SERVICES: ServiceDefinition[] = [
  {
    id: 'service-07',
    number: '07',
    title: '누수탐지·복구 예상비용',
    slug: 'leak-detection',
    categoryId: 'plumbing',
    categoryName: '누수·배관·수도',
    ruleId: 'rule-leak-detection',
    shortDesc: '아랫집 천장 물샘, 공압·청음·가스 정밀 누수탐지 및 배관 수리 복구 견적',
    icon: '💧',
    questions: [
      {
        id: 'leak_location',
        label: '의심 누수 위치 및 증상',
        type: 'select',
        defaultValue: 'ceiling_drip',
        options: [
          { label: '아랫집 천장 도배지가 젖거나 물이 뚝뚝 떨어짐', value: 'ceiling_drip', priceDelta: 300000 },
          { label: '수도요금이 갑자기 폭탄으로 많이 나옴', value: 'water_bill', priceDelta: 250000 },
          { label: '보일러 난방수 보충(에러코드) 지속 발생', value: 'boiler_leak', priceDelta: 280000 },
          { label: '화장실 바닥 타일 틈새 방수층 의심 누수', value: 'bathroom_waterproof', priceDelta: 350000, hint: '비파괴 방수 침투제 또는 타일 재시공' },
        ],
        required: true,
      },
      {
        id: 'equipment_type',
        label: '탐지 장비 및 방식',
        type: 'select',
        defaultValue: 'acoustic_gas',
        options: [
          { label: '기본 청음식 탐지 (공기압력 검사 + 청음기)', value: 'acoustic_only', priceDelta: 0 },
          { label: '청음식 + 가스 추적 정밀 탐지 (미세 누수 전문)', value: 'acoustic_gas', priceDelta: 100000, hint: '오차 10cm 이내 정확한 핀포인트 탐지' },
          { label: '열화상 카메라 진단 + 배관 내시경', value: 'thermal_scope', priceDelta: 150000 },
        ],
        required: true,
      },
      {
        id: 'repair_work',
        label: '굴착 수리 및 복구 포함 여부',
        type: 'select',
        defaultValue: 'excavation_repair',
        options: [
          { label: '누수 위치 탐지만 진행 (수리는 별도)', value: 'detect_only', priceDelta: 0 },
          { label: '탐지 + 바닥 굴착 배관 연결 수리 + 미장 마감', value: 'excavation_repair', priceDelta: 200000, hint: '가장 많은 표준 원스톱 작업' },
          { label: '탐지 + 굴착 수리 + 아랫집 천장 도배 복구 지원', value: 'full_insurance', priceDelta: 450000, hint: '일상생활배상책임보험 청구 패키지' },
        ],
        required: true,
      },
    ],
    evidence: {
      provider: '숨고(Soomgo) 누수 탐지/공사 시세 빅데이터',
      sourceUrl: 'https://soomgo.com/prices/%EB%88%84%EC%88%98-%ED%83%90%EC%A7%80',
      basePrice: 300000,
      minPrice: 150000,
      maxPrice: 800000,
      priceUnit: '건당 150,000원 ~ 800,000원 (기본 탐지 평균 30만)',
      vatIncluded: true,
      travelFeeIncluded: true,
      materialsIncluded: true,
      surveyedAt: '2026-09-01',
      lastVerifiedAt: '2026-10-09',
      verificationStatus: 'verified',
      reliabilityLevel: 'medium',
      sourceType: 'platform_average',
      notes: '숨고 실거래 평균 300,000원(최저 150,000원~최고 800,000원). 청음/가스식 위치 탐지만 진행 시 30만원대, 굴착 배관수리 및 바닥 복구 포함 시 50만~80만원 선.',
    },
    seo: {
      title: '누수탐지 비용 견적 계산기 (아랫집 물샘/탐지비용/보험처리) | 바로견적',
      description: '아파트, 빌라 아랫집 천장 누수탐지비용, 가스식 정밀탐지, 배관 굴착 수리 및 일상배상책임보험 청구 예상비용을 확인하세요.',
      keywords: ['누수탐지 비용', '누수 공사비용', '아랫집 물샘 수리비', '누수탐지 못찾으면', '누수 보험처리 일배책'],
      h1: '누수탐지·복구 예상비용 계산기',
      canonicalPath: 'https://quote.info-myview.co.kr/estimate/leak-detection/',
      faq: [
        {
          question: '누수 위치를 못 찾아도 출장비를 줘야 하나요?',
          answer: '실력 있는 전문 누수 탐지 업체는 "누수 지점을 찾아내지 못하면 비용을 일체 받지 않는다(0원)"는 조건을 표준 계약으로 제시합니다.',
        },
        {
          question: '아랫집 피해 도배 비용도 보험으로 보상받을 수 있나요?',
          answer: '네. 가입해 두신 실손의료비나 운전자보험의 "가족일상생활배상책임(일배책)" 특약을 통해 누수 탐지 수리비(손해방지비용) 및 아랫집 도배 복구비용을 자기부담금을 제외하고 보상받을 수 있습니다.',
        },
        {
          question: '누수 탐지 작업 시간은 얼마나 걸리나요?',
          answer: '보통 공압 검사 30분, 가스 주입 및 청음 탐지 1~2시간, 굴착 후 배관 부분 연결 수리까지 총 3~5시간 정도 소요됩니다.',
        },
        {
          question: '난방 배관과 수도 배관 중 어디서 누수가 더 자주 발생하나요?',
          answer: '온수 배관(PPC/동배관)의 수축 팽창 피로 파손이 가장 흔하며, 그 다음으로 직수 배관, 난방 배관 순입니다.',
        },
      ],
    },
  },
  {
    id: 'service-11',
    number: '11',
    title: '수전·수도설비 교체비용',
    slug: 'faucet-replacement',
    categoryId: 'plumbing',
    categoryName: '누수·배관·수도',
    ruleId: 'rule-faucet-replacement',
    shortDesc: '싱크대 원홀 수전, 세면대 수전, 샤워기 수전 교체 공임 및 국산 부품비',
    icon: '🚰',
    questions: [
      {
        id: 'faucet_type',
        label: '교체할 수전 유형',
        type: 'select',
        defaultValue: 'sink_onehole',
        options: [
          { label: '주방 싱크대 원홀 거위목/자바라 수전', value: 'sink_onehole', priceDelta: 45000 },
          { label: '욕실 세면대 원홀/겸용 샤워 수전', value: 'washbasin', priceDelta: 40000 },
          { label: '욕실 샤워기 벽붙이 수전', value: 'shower_wall', priceDelta: 45000 },
          { label: '레인샤워 해바라기 샤워기 타공 설치', value: 'rain_shower', priceDelta: 80000, hint: '기둥 지지대 벽 타공 작업 포함' },
        ],
        required: true,
      },
      {
        id: 'supply_type',
        label: '수전 제품 준비 방식',
        type: 'select',
        defaultValue: 'product_included',
        options: [
          { label: '고객 직접 준비 (단순 교체 공임만 의뢰)', value: 'labor_only', priceDelta: 0 },
          { label: '업체 지참 (국산 KS 인증 황동 내구성 제품 포함)', value: 'product_included', priceDelta: 55000, hint: '수전 본체 + 부속품 일체' },
          { label: '고급형 무광 니켈 / 거위목 디자이너 수전 포함', value: 'premium_included', priceDelta: 110000 },
        ],
        required: true,
      },
      {
        id: 'valve_condition',
        label: '수도 계량기 및 앵글밸브 노후 상태',
        type: 'select',
        defaultValue: 'normal',
        options: [
          { label: '정상 (기존 밸브 재사용 가능)', value: 'normal', priceDelta: 0 },
          { label: '녹슬어 고착됨 (조절 앵글밸브 신규 교체 필요)', value: 'valve_replace', priceDelta: 20000, hint: '누수 방지 밸브 2개 신품 교체' },
        ],
        required: true,
      },
    ],
    evidence: {
      provider: '숨고(Soomgo) 수도 관련 설치 및 수리 시세 빅데이터',
      sourceUrl: 'https://soomgo.com/prices/%EC%88%98%EB%8F%84-%EC%84%A4%EC%B9%98-%EC%88%98%EB%A6%AC',
      basePrice: 85000,
      minPrice: 45000,
      maxPrice: 260000,
      priceUnit: '건당 45,000원 ~ 260,000원 (공임+기본부품 평균 8.5만)',
      vatIncluded: true,
      travelFeeIncluded: true,
      materialsIncluded: true,
      surveyedAt: '2026-09-01',
      lastVerifiedAt: '2026-10-09',
      verificationStatus: 'verified',
      reliabilityLevel: 'high',
      sourceType: 'platform_average',
      notes: '숨고 실거래 평균 85,000원(단순교체 최저 45,000원~최고 260,000원). 수전 고객 준비 시 공임만 4.5만~6만, 국산 정품 황동 수전 포함 시 8.5만~13만.',
    },
    seo: {
      title: '수전 교체비용 견적 계산기 (주방 싱크대/세면대/샤워기) | 바로견적',
      description: '싱크대 원홀 수전, 욕실 세면기, 해바라기 샤워기 교체 출장 공임 및 부품비 포함 가격을 계산해보세요.',
      keywords: ['수전 교체비용', '싱크대 수전 교체', '세면대 수도꼭지 교체', '샤워기 교체 공임', '수전 설치비'],
      h1: '수전·수도설비 교체비용 계산기',
      canonicalPath: 'https://quote.info-myview.co.kr/estimate/faucet-replacement/',
      faq: [
        {
          question: '인터넷에서 산 수전을 기사님께 설치만 부탁해도 되나요?',
          answer: '네. 제품을 직접 구매해 두신 경우 단순 출장 교체 공임(통상 4만~6만원)만 지불하시면 깔끔하게 시공해 드립니다.',
        },
        {
          question: '셀프 교체하다가 물이 새는 가장 흔한 이유는 무엇인가요?',
          answer: '수전 호스를 조일 때 패킹 고무가 씹히거나 테프론 테이프를 제대로 감지 않은 경우, 또는 노후된 벽면 앵글밸브 나사산이 부러져 누수가 발생하는 경우가 많습니다.',
        },
        {
          question: '기존 고장난 수전은 수거해 주시나요?',
          answer: '네. 교체 작업 후 탈거한 고품 고철 수전은 기사님이 무상으로 수거 및 폐기 처리해 드립니다.',
        },
        {
          question: '작업 시간은 얼마나 걸리나요?',
          answer: '고착이 없는 일반적인 싱크대나 세면대 수전 교체는 약 20분~40분 내에 완료됩니다.',
        },
      ],
    },
  },
  {
    id: 'service-22',
    number: '22',
    title: '하수구·배관 막힘 처리비용',
    slug: 'drain-unclogging',
    categoryId: 'plumbing',
    categoryName: '누수·배관·수도',
    ruleId: 'rule-drain-unclogging',
    shortDesc: '싱크대 역류, 변기 막힘, 욕실 배수구, 메인 오수관 전동 스프링·석션·고압세척',
    icon: '🚽',
    questions: [
      {
        id: 'blockage_location',
        label: '막힘 발생 위치',
        type: 'select',
        defaultValue: 'sink_clog',
        options: [
          { label: '주방 싱크대 하부 배관 (기름 슬러지 역류)', value: 'sink_clog', priceDelta: 60000 },
          { label: '화장실 변기 (이물질·플라스틱 빠짐)', value: 'toilet_clog', priceDelta: 40000 },
          { label: '욕실 바닥 배수구 / 세탁실 하수구', value: 'bathroom_drain', priceDelta: 50000 },
          { label: '빌라·건물 1층 메인 횡주관 / 외부 집수정 역류', value: 'main_pipe', priceDelta: 200000, hint: '공용배관 전체 고압세척' },
        ],
        required: true,
      },
      {
        id: 'equipment_level',
        label: '투입 장비 수준',
        type: 'select',
        defaultValue: 'suction_snake',
        options: [
          { label: '기본 장비 (석션 흡입기 + 수동 와이어)', value: 'basic', priceDelta: 0 },
          { label: '전동 샤프트 스케일링 + 배관 내시경 카메라 확인', value: 'suction_snake', priceDelta: 70000, hint: '배관 내부 확인 및 재발 방지' },
          { label: '배관 엔진 고압 세척 (배관 신품 수준 복원)', value: 'hydro_jet', priceDelta: 150000, hint: '기름 슬러지 완벽 박멸' },
        ],
        required: true,
      },
      {
        id: 'urgency_level',
        label: '출동 긴급도',
        type: 'select',
        defaultValue: 'normal',
        options: [
          { label: '일반 주간 방문 (영업시간 내)', value: 'normal', priceDelta: 0 },
          { label: '심야 / 야간 긴급 출동 (역류 피해 방지)', value: 'night_emergency', priceDelta: 40000, hint: '당일 야간 출장 할증' },
        ],
        required: true,
      },
    ],
    evidence: {
      provider: '숨고(Soomgo) 하수구 청소 시세 빅데이터',
      sourceUrl: 'https://soomgo.com/prices/%ED%95%98%EC%88%98%EA%B5%AC-%EC%B2%AD%EC%86%8C',
      basePrice: 50000,
      minPrice: 50000,
      maxPrice: 300000,
      priceUnit: '건당 (평균 5만원 / 최저 5만 ~ 최고 30만원)',
      vatIncluded: true,
      travelFeeIncluded: true,
      materialsIncluded: true,
      surveyedAt: '2026-10-09',
      lastVerifiedAt: '2026-10-09',
      verificationStatus: 'verified',
      reliabilityLevel: 'high',
      sourceType: 'platform_average',
      notes: '숨고 실거래 평균 50,000원 (최저 5만 ~ 최고 30만원). 단순 변기 관통 5만~7만, 싱크대 전동 샤프트 스케일링 12만~18만, 메인 오수관 고압세척 30만.',
    },
    seo: {
      title: '하수구 뚫음 비용 견적 계산기 (싱크대역류/변기/고압세척) | 바로견적',
      description: '싱크대 하부 배관 역류, 변기 이물질 막힘, 하수구 내시경 관통 및 고압세척 장비별 예상비용을 확인하세요.',
      keywords: ['하수구 뚫는 비용', '싱크대 막힘 해결 비용', '변기 뚫음 가격', '하수구 고압세척 견적', '배관 내시경 비용'],
      h1: '하수구·배관 막힘 처리비용 계산기',
      canonicalPath: 'https://quote.info-myview.co.kr/estimate/drain-unclogging/',
      faq: [
        {
          question: '싱크대 물이 안 내려가고 바닥으로 역류하는 원인은 무엇인가요?',
          answer: '기름기 있는 음식물 조리 후 버린 기름이 배관 속에서 굳어 비누처럼 굳은 딱딱한 기름 슬러지가 원인입니다. 단순 액체 약품으로는 녹지 않아 전동 플렉스 샤프트나 고압 석션기로 파쇄 흡입해야 합니다.',
        },
        {
          question: '변기에 칫솔이나 화장품 뚜껑이 들어갔을 땐 어떻게 하나요?',
          answer: '뚫어뻥을 무리하게 누르면 이물질이 변기 S트랩 더 깊은 곳에 꽉 끼게 됩니다. 초강력 석션기로 역흡입하여 빼내야 변기 뜯음(탈거) 비용(10만~15만)을 아낄 수 있습니다.',
        },
        {
          question: '뚫고 나서 얼마 안 가 다시 막히면 A/S가 되나요?',
          answer: '전문 업체는 내시경으로 배관 청소 상태를 고객에게 확인시켜 주며, 통상 1~3개월 동일 원인 막힘에 대해 무상 A/S를 보증합니다.',
        },
        {
          question: '고압세척은 언제 필요한가요?',
          answer: '빌라 1층 역류나 상가 식당 배관처럼 수년간 쌓인 유지방 덩어리가 직경 100mm 이상 배관을 꽉 채웠을 때 온수 고압수로 배관 전체를 세척합니다.',
        },
      ],
    },
  },
];
